### ISSUE TITLE
Lag on sending messages through Android (server 0.1.10, PlayStore release, macOS 14.6, Android 10/OneUI 2.5)

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Server#107]
I converted this video to a gif but the file size was too big to attach. See my issue [here](https://streamable.com/8cewmh)

**Comment by CSab6482** [comment]
I also receive this error when closing the app
![Image 11-29-20 at 10 57 PM](https://user-images.githubusercontent.com/53708281/100567562-c108e180-3296-11eb-873e-198fd0bb14ae.jpeg)

**Comment by zlshames** [comment]
@CSab6482 I am currently working on a nightly build to hopefully help fix this issue. I will keep the Discord updated, so go there to get the nightly build when it's available.

**Comment by CSab6482** [comment]
Thank you!
