### ISSUE TITLE
Cannot send contact vcf files on Android

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Server#110]
In this video, the app simply exits whenever I tap the vcf file
![No VCF](https://user-images.githubusercontent.com/53708281/101115394-49e28e80-35b1-11eb-956e-2e1d24e9a16a.gif)

**Comment by zlshames** [comment]
This is also an issue with the Android App. Moving it there. Closing this one. here is the new link: https://github.com/BlueBubblesApp/BlueBubbles-Android-App/issues/530
