### ISSUE TITLE
Images sent with subject line text but no main body text don't show any text

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Server#111]
Photos with text in the subject line and no text in the main body do not display any text [as seen here.](https://i.imgur.com/9zsUU0q.mp4) If there is text in both the subject line and main body, then it shows up.

**Comment by CSab6482** [comment]
I have a similar problem when there is subject line text and only emojis in the main body, [video here.](https://i.imgur.com/dpOrlLD.mp4)

**Comment by zlshames** [comment]
I believe this is an issue with the Android App (client-side). I will move this ticket over there. Closing. Here is the new ticket link: https://github.com/BlueBubblesApp/BlueBubbles-Android-App/issues/529
