### ISSUE TITLE
Emit newGuid back to clients after sending message through private api

### ISSUE THREAD

**Issue by maxwellfortney** [BlueBubblesApp/bluebubbles-server#144]
https://github.com/BlueBubblesApp/BlueBubbles-Server/blob/b8c483095beaad99399740ee6453abc98f0ff147/src/main/server/services/helperProcess/index.ts#L199

The chatGuid, tempGuid, and newGuid for the recently sent message are received by the server here ^.

**Comment by tneotia** [comment]
not necessary with rest api
