### ISSUE TITLE
Update button shows update when on latest

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Server#150]
https://cdn.discordapp.com/attachments/782690923640782878/797474808585256980/Screen_Shot_2021-01-09_at_9.38.41_AM.png

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#server-bugs`.

**Comment by zlshames** [comment]
I believe I fixed this. Closing. It wasn't comparing the updates correctly
