### ISSUE TITLE
Sender names missing from newly created chats & tapping on a received picture opens a different picture

### ISSUE THREAD

**Issue by lepotter** [BlueBubblesApp/BlueBubbles-Server#159]
After creating a newly created chat (in the most recent nightly app), received messages do not show sender names. Also, when receiving a picture, tapping on the picture opens a different picture. Restarting the app fixes this and the sender names appear and tapping the picture will open the correct picture.

**Comment by zlshames** [comment]
I assume this has been fixed. Closing. If not, comment here and I will re-open it.
