### ISSUE TITLE
High DNS Usage to Google.com

### ISSUE THREAD

**Issue by onfire4g05** [BlueBubblesApp/BlueBubbles-Server#167]
I've been seeing a huge spike in my DNS requests to `www.google.com` and finally got around to figuring out what the issue was. I've not researched this a whole lot, but I believe it's related to this:

https://github.com/BlueBubblesApp/BlueBubbles-Server/blob/6500a495a67a4049ad677102c90e719e23c56e8a/src/main/server/services/network/index.ts#L36

Is there any way this could be either customizable in length for the check (maybe 5 minutes vs 5 seconds) or possibly use another method to check for internet connectivity?

I'm running two instances of BlueBubbles, so I'm literally sending about 35k dns requests to my poor AdGuard server every day.

**Comment by zlshames** [comment]
I'm increasing this to 1 minute. Eventually will make it toggleable
