### ISSUE TITLE
Throw an error when an attachment is larger than 100 mb

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-server#168]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#nightly-bugs`.

**Comment by tneotia** [comment]
I've taken care of this client side now, but might still be good for REST API endpoints

**Comment by tneotia** [comment]
we dont need to do this as imessage can send larger videos (compresses them)
