### ISSUE TITLE
Add this to FAQ

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-server#170]
https://github.com/toshmatik/VMWare-iMessage/blob/master/instructions.md

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#support`.

**Comment by CSab6482** [comment]
https://www.reddit.com/r/BlueBubbles/comments/m40152/vmware_guide_how_to_set_up_a_mac_vm_in_vmware/
https://discord.com/channels/640229510662455326/640229510662455328/821847978519167017
