### ISSUE TITLE
video transcoding when sending

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-server#181]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#support`.

**Comment by Vicvinegar0** [comment]
iMessage does not seem to like videos created with (probably not limited to) Google Cam. 
However changing the color profile metadata allows the videos to send fine

See https://github.com/streamio/streamio-ffmpeg/issues/205

Would be great if BB could allow the checking and changing of this metadata before sending it over iMessage

**Comment by zlshames** [comment]
The problem with bundling ffmpeg is that the binary for it is fairly large and adds a good bit of size to the app. I've tried to do it when sending mov videos and it works, but in this case, im not sure how i'd detect a google cam video and convert it.
