### ISSUE TITLE
use file hashes to determine if a file is a duplicate, in which case the entire file does not need to be sent

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-server#182]
if file hashes match, the server could just send the hash, or some other, smaller indicator. if the client doesn't have the file, they can always download it after the fact by request with the current protocol.

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@isaac` in `#requests`.

**Comment by zlshames** [comment]
I dont think this is something we need to do anymore tbh
