### ISSUE TITLE
handle incorrect ngrok keys more cleanly

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-server#183]
currently, if the ngrok Auth key is entered incorrectly by the user, the server will not show any error, and just repeatedly restart every few seconds until the typo is fixed. it would probably be better to have an error message that the key is incorrect.

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@electronika` in `#server-bugs`.

**Comment by zlshames** [comment]
Done, when an invalid key is detected, the field will auto clear and an error will show in the logs
