### ISSUE TITLE
[Rewrite] Duck DNS + ngrok plugin

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-server#185]
https://gist.github.com/Rihcus/4a217e0092e1fa34299e395222759165

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#requests`.

**Comment by zlshames** [comment]
While this is useful, I think it's probably better to just use their DUC rather than having it implemented in the app
