### ISSUE TITLE
When reacting to a link, reaction messages show up incorrect

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-server#191]
They will often times show as `x liked an image`, which is incorrect.

From @sgtaziz:

I'm not sure how helpful this will be, as my experience is from iOS side as opposed to macOS.

When sending a reaction, you are usually passing a summaryInfo variable. This variable is what handles showing "Liked an attachment" or "Liked 'Hi!'"

```
// First, you need to enter the string the user is reacting to in the summerInfo "ams" key.
// I am replacing \ufffc with an empty string to remove the unicode character added by attachments.
summaryInfo[@"ams"] = [[textMsg string] stringByReplacingOccurrencesOfString:@"\ufffc" withString:@""];

// You will also need to pass the "amc" key as a boolean. If it is true (or @1), it will react to an attachment.
// If it is false (or @0), it will react to a text message.
summaryInfo[@"amc"] = [summaryInfo[@"ams"] length] == 0 ? @0 : @1;
```

Yeah I'm not sure why the invisible Unicode character even exists. The NSAttributedString is enough to place attachments where needed, but ¯_(ツ)_/¯

**Comment by CSab6482** [comment]
This is not just for links, but for all messages. Reacting to a text message sends a notification of `X liked an attachment`. Below is a message from Syna#6283 in the Discord, along with the screenshots they attached.
![image](https://user-images.githubusercontent.com/53708281/124962235-62ee6a80-dfec-11eb-9df5-bcc71eddf082.png)
![1](https://cdn.discordapp.com/attachments/783071225803046944/796772042590126131/Snapchat-1462799787.jpg)
![2](https://cdn.discordapp.com/attachments/783071225803046944/796772116602552330/Snapchat-1856104970.jpg)
Interestingly enough, however, WebMessage works past this bug and correctly shows the message that received the reaction. Below is an example of MyMessage on the left and WebMessage on the right.
![Tapback](https://user-images.githubusercontent.com/53708281/124962501-b3fe5e80-dfec-11eb-94fa-42e020af8ce8.png)
and on iOS, it only says `You loved an attachment`
![IMG_0825](https://user-images.githubusercontent.com/53708281/124962695-f1fb8280-dfec-11eb-92b0-43815167977e.jpg)
WebMessage's ability to always be correct with the conversation history was also noted [here](https://github.com/open-imcore/imcore.react/issues/5#issuecomment-823480420). I'm really curious to know how @sgtaziz was able to accomplish this.

And now just some miscellaneous links.
https://github.com/BlueBubblesApp/BlueBubbles-Android-App/issues/823
https://github.com/sgtaziz/WebMessage/issues/51#issuecomment-782634724
https://discord.com/channels/640229510662455326/783071225803046944/817454134499475468

**Comment by zlshames** [comment]
I believe @tneotia fixed it with the latest bundle updates (at least for Big Sur). We just need to do the same for catalina and lower
