### ISSUE TITLE
set ngrok region https://ngrok.com/docs#global-locations

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Server#199]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@Deemo` in `#baffoonery`.

**Comment by Rihcus** [comment]
Sory for forgetting to add the description (new to the bot). I was wondering if it would be possible to add a ui option to select between ngrok regions. This may be particularly usefull if your traviling out of country as it may potentially improove peering depending on the isp of traviling country. 

Regions for Ngrok:
    us - United States (Ohio)
    eu - Europe (Frankfurt)
    ap - Asia/Pacific (Singapore)
    au - Australia (Sydney)
    sa - South America (Sao Paulo)
    jp - Japan (Tokyo)
    in - India (Mumbai)

https://ngrok.com/docs#global-locations
https://ngrok.com/docs#config-location

https://ngrok.com/docs#config-examples (under Example configuration file with all options)
