### ISSUE TITLE
import messages from Big Sur to Catalina

### ISSUE THREAD

**Issue by iambenmitchell** [BlueBubblesApp/bluebubbles-server#234]
Hello, because I want to use private API features, I cannot use an OS higher than Catalina if I recall correctly. However, in Catalina, there is no iMessage iCloud sync support.

Therefore I want to download the messages on a separate Big Sur server and then send them over to the Catalina one running BlueBubbles.

I have downloaded all the messages on Big Sur and archived ~/Library/Messages. I then sent this over to the Catalina server. I then deleted the existing ~/Library/Messages and replaced it with the Big Sur one and rebooted the server.

However, when I open the iMessage app, all the conversations are gone. It is blank.

My question is, do you know how to import my messages into Catalina?

**Comment by zlshames** [comment]
> Hello, because I want to use private API features, I cannot use an OS higher than Catalina if I recall correctly. However, in Catalina, there is no iMessage iCloud sync support.
> 
> Therefore I want to download the messages on a separate Big Sur server and then send them over to the Catalina one running BlueBubbles.
> 
> I have downloaded all the messages on Big Sur and archived ~/Library/Messages. I then sent this over to the Catalina server. I then deleted the existing ~/Library/Messages and replaced it with the Big Sur one and rebooted the server.
> 
> However, when I open the iMessage app, all the conversations are gone. It is blank.
> 
> My question is, do you know how to import my messages into Catalina?

The chat.db files are different on Catalina and Big Sur. I'm not sure you can just transfer them and have it work. The only way to do that would be to use iCloud Message Sync I believe. 

@tneotia is working on fixing the bundle to run on big sur. So look out for that
