### ISSUE TITLE
render hevc-> mp4 on server instead of using android's built in one

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-server#253]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@monicow` in `#android-support`.

**Comment by zlshames** [comment]
Can't do this. iMessage on macOS Big Sur (and I assume lower) doesn’t even recognize the mime type for hevc videos. So we can't hook into when one is sent/received
