### ISSUE TITLE
Doesn't seem to be recoverable: go thru wizard, select dyanmic DNS, enter the wrong URL.  URL doesn't seem to be editable after making a mistake in entering the URL

### ISSUE THREAD

**Issue by arooni** [BlueBubblesApp/bluebubbles-server#284]
Am I missing something obvious?

Server 0.4.0 on El Capitan.

I can't seem to edit the server URL field, or even pick a different method like ngrok etc.

**Comment by arooni** [comment]
There is a small drop down on the config page I missed :P

**Comment by zlshames** [comment]
Yep, you're right, i should add a button next to the field to manually set it :)
