### ISSUE TITLE
Server not displaying best friend

### ISSUE THREAD

**Issue by dacmcbibs** [BlueBubblesApp/bluebubbles-server#315]
I don't have any of my contacts loaded on my mac.  Previously it would show the phone number, in the current stable build it just tries to load forever.  
The dev tools show the following error:  Uncaught (in promise) TypeError: Cannot read properties of null (reading 'firstName')
    at HomeLayout.tsx:71

**Comment by zlshames** [comment]
Fixed: `zach/315/best-friend-fix`
