### ISSUE TITLE
[REST API] [Private API Send] Do not send 200 success response when a message has an error attached to it

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-server#325]
easiest way to test is to send to a non-imessage number, server will still send 200 success

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@tneot01` in `#server-development`.

**Comment by zlshames** [comment]
Fixed, branch: `zach/325/send-proper-status`
