### ISSUE TITLE
[Private API] Delete chat endpoint

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-server#328]
Private api requires `delete-chat` as the event, and the chat GUID as data. When complete, private API will send the transaction ID, and nothing more, back from the socket so the server can respond back to the requestor with 200.

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@tneot01` in `#general`.

**Comment by zlshames** [comment]
I added the delete chat endpoint, however, it's currently setup to just delete the chat directly from the DB. Now, I don't know the full repercussions of doing it this way, so I've disabled the endpoint for the time being.

**Comment by tneotia** [comment]
Can you add support for private api to do this - I've updated the bundle to support it, we just need server to handle the request to private API. Shouldn't be too difficult.

**Comment by zlshames** [comment]
@tneotia the payload to the helper is a dictionary, so I have to pass something like `{ guid: "iMessage;-;123123123" }`. Other than that, It's implemented. I haven’t tested it yet. Code is in the `zach/328/chat-delete-api` branch and I'll get it into the next build to test
