### ISSUE TITLE
Make sure password with special characters can be handled in API request

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-server#340]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@tneot01` in `#support`.

**Comment by zlshames** [comment]
We already escape most characters. Are there specific ones people are using that we don't, but need to be?

**Comment by zlshames** [comment]
Apparently the offending character is a `#`

**Comment by zlshames** [comment]
Tested this and I think the user was not URI encoding their URL parameters
