### ISSUE TITLE
Mark chat as read endpoint returns 404

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-server#342]

**Comment by zlshames** [comment]
@tneotia Can you try my latest server to reproduce this? I need more info on this since I don't dev on a mac with SIP disabled. Does it still return a 404? When I hit the endpoint, it doesn't, but it also doesn't execute the private api code. It just errors out (normally, and as it should).

**Comment by tneotia** [comment]
@zlshames yes I still get error on latest server and still is a 404. I do see in BB Helper logs that it received a request to mark the chat as read, and processed it successfully.
