### ISSUE TITLE
Server cannot run Applescript and thus cannot send messages

### ISSUE THREAD

**Issue by gjlowe** [BlueBubblesApp/bluebubbles-server#360]
After the 11.6.5 update I know they made some changes to Applescript, and when trying to reset my bluebubbles server, I can't get it to send messages or accept another FCM file.  If I look at the logs I see

"osascript:  can't open default scripting component"

Also, the errors I get when I try to add the google-services.json file again are in the attached screenshots

<img width="673" alt="Screen Shot 2022-05-06 at 9 38 59 AM" src="https://user-images.githubusercontent.com/3599527/167271967-5dd44b0a-6c3a-46a3-a5ad-30e5575d5ad8.png">

<img width="480" alt="Screen Shot 2022-05-06 at 9 37 21 AM" src="https://user-images.githubusercontent.com/3599527/167271972-5c8995aa-f388-4d92-9d4c-d39db3b58fd4.png">

.

**Comment by gjlowe** [comment]
One more screenshot:

<img width="1079" alt="Screen Shot 2022-05-06 at 9 15 31 AM" src="https://user-images.githubusercontent.com/3599527/167271977-315ee803-d1d9-4cea-9b1b-5bf7ab5d223c.png">

**Comment by zlshames** [comment]
This typically means that BlueBubbles does not have the correct permissions to access the filesystem. Can you ensure that BB has full disk permissions

**Comment by zlshames** [comment]
ok, i think often times after upgrades, system settings are messed up until a reboot. Closing this.
