### ISSUE TITLE
Native apple silicon support

### ISSUE THREAD

**Issue by anonymousaga** [BlueBubblesApp/bluebubbles-server#383]
Could we get a server app that supports apple silicon natively or is a universal binary? I am noticing that intel apps use a large amount of ram (around 500 MB) at idle, while native apps consume closer to 200mB at idle. Many thanks for considering my request.

**Comment by zlshames** [comment]
From what I understand, apple silicon should be supported. We have a handful of users utilizing m1 macs. Is there a specific issue you are having or just high memory utilization?

**Comment by anonymousaga** [comment]
It is working with rosetta, just high RAM usage. I was wondering if I could somehow build it myself for native apple silicon or if you could release an apple silico binary.n

**Comment by zlshames** [comment]
According to this article, it hopefully should just be a buid configuration: https://www.electronjs.org/blog/apple-silicon

**Comment by anonymousaga** [comment]
I'm quite unfamiliar with npm, yarn, & electron, so do you think you can try changing this parameter & rebuilding? Thanks in advance. I'd be happy to test for bugs in the m1 version if you'd like.

**Comment by zlshames** [comment]
> Yeah, that would be great! Should I close this now or after the update? Thanks.

nope, i'll close it when it's officially implemented. thanks

**Comment by zlshames** [comment]
@anonymousaga so I was able to build for arm64 (apple silicon), however, I have a few things to note:

1. Would you be willing to test it?
2. binaries that we rely on such as ngrok or cloudflare may or may not work (untested). But maybe you can help test.

**Comment by anonymousaga** [comment]
Yes, i would be willing to test. I use ngrok for the app.

**Comment by zlshames** [comment]
> Yes, i would be willing to test. I use ngrok for the app.

are you in our discord?

**Comment by anonymousaga** [comment]
No, should i join?

**Comment by zlshames** [comment]
> No, should i join?

yes please, it will make communications much easier

**Comment by anonymousaga** [comment]
Ok, i am in there as cos(A+B)=cosA*cosB-sinA*sinB#1100

**Comment by anonymousaga** [comment]
"cos(A+B)=cosA*cosB-sinA*sinB#1100"

**Comment by azinman** [comment]
Any updates? This was 1.5 years ago and it's still being distributed as intel only.

**Comment by zlshames** [comment]
> Any updates? This was 1.5 years ago and it's still being distributed as intel only.

I think I would need an Apple Silicon mac to build it, and I don't have one

**Comment by zlshames** [comment]
I was able to properly implement arm64 support. It requires using `npm` and not `yarn` for some reason. Dropping yarn support.

**Comment by anonymousaga** [comment]
Approximately when will this build make its way to the release version? Thanks!

**Comment by zlshames** [comment]
> Approximately when will this build make its way to the release version? Thanks!

im working on finalizing some stuff. If you'd like to test it out (cuz I'd like to get at least 1 or 2 testers), please DM me via Discord
