### ISSUE TITLE
Home-brew support

### ISSUE THREAD

**Issue by anonymousaga** [BlueBubblesApp/bluebubbles-server#384]
Could you make this app a homebrew cask file so that it can be installed via homebrew?

I have already created a working rb file if you would like to use, but you should probably add some uninstall instructions such as removing it from the login items list & deleting the library folder: [Brew Uninstall Stanza Directions](https://docs.brew.sh/Cask-Cookbook#stanza-uninstall). You should probably also add a sha256 hash.

Here is the cask .rb file I created:
[bluebubbles.rb.zip](https://github.com/BlueBubblesApp/bluebubbles-server/files/9035134/bluebubbles.rb.zip)

You also have passed the audit, so you most likely will be accepted into the homebrew-cask repo.

**Comment by zlshames** [comment]
Thanks for the suggestion & rb! I'll have to look further into this. Not crazy familiar with homebrew at the moment

**Comment by zlshames** [comment]
BB is now available on Homebrew

**Comment by anonymousaga** [comment]
Thanks!
