### ISSUE TITLE
Option to disable notifications

### ISSUE THREAD

**Issue by anonymousaga** [BlueBubblesApp/bluebubbles-server#389]
I keep the app in the dock so that I can have AppleScript close the window on launch. However, I dont like the red bubble with those normal error notifications. Is there any way to disable this red icon in the dock icon for notifications that I do not need to address? I cannot find BlueBubbles in the notifications preferences.

**Comment by zlshames** [comment]
![CleanShot 2022-08-11 at 15 51 51](https://user-images.githubusercontent.com/18445938/184227300-0b2d6977-59e2-4576-9b11-f0aa243e2307.gif)

Done

**Comment by anonymousaga** [comment]
Is this already there, or will it be released in a future update? Is there an approx time for this update? Thanks in advance.

**Comment by zlshames** [comment]
> Is this already there, or will it be released in a future update? Is there an approx time for this update? Thanks in advance.

The development work is done. Just needs to make its' way into a release. I have no ETA, but I assume it shouldn't be too long
