### ISSUE TITLE
Doesn't recover after network outage

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-server#393]
![image](https://media.discordapp.net/attachments/782690923640782878/999803189001977896/unknown.png)

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@tneot01` in `#server-support`.

**Comment by zlshames** [comment]
Im not sure this error is relevant to the title of the ticket. At least it doesn't provide much. Do you know during your network outage if your mac ever disconnected from the network? or was it always connected, and just couldn't provide internet?

**Comment by zlshames** [comment]
@tneotia what proxy service was this?

**Comment by tneotia** [comment]
This is ngrok. I don't think my Mac would've disconnected because it doesn't have any other saved networks
