### ISSUE TITLE
add button to firebase links

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-server#396]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#feedback`.

**Comment by zlshames** [comment]
I can't do this because the links are project-specific

**Comment by zlshames** [comment]
I take this back. apparently you can use underscores to let the site know to let the user choose a project before redirecting

**Comment by zlshames** [comment]
Done, development branch
