### ISSUE TITLE
Feature Request: Check if MacForge is running for Private API Check

### ISSUE THREAD

**Issue by ahatzz11** [BlueBubblesApp/bluebubbles-server#401]
👋  I've had my computer restart a couple of times and I've noticed that MacForge doesn't automatically start properly. I do have the setting for it to start on launch, but it doesn't seem to be the same as opening/starting MacForge after boot. When this happens, the Private API features on my mobile device stop working, so I end up manually turning off the Private API Message Send feature as a workaround until I get back to my server.

Macforge Setting:
![image](https://user-images.githubusercontent.com/6256032/186186166-48c7ac8d-6f85-496c-8e35-e88b9bfaedc5.png)

It would be awesome if BlueBubbles did a third check for the "Private API Requirements" for MacForge actually running. Something here:
![image](https://user-images.githubusercontent.com/6256032/186186277-e82fb94a-8857-4c10-b7b8-ba5adfdfe68c.png)

**Comment by zlshames** [comment]
sure, I can see if it's possible
