### ISSUE TITLE
Removing participants from group gives error "Failed to remove participant: null"

### ISSUE THREAD

**Issue by SprintKeyz** [BlueBubblesApp/bluebubbles-server#407]
Not sure if a fix was intended to be shipped in server version v1.2.0, but the error message is different. I don't get any error on the server itself (MacOS Big Sur), however, when I enable logging on my phone, this is the result:

```
[BlueBubblesApp] [INFO] (REQUEST[POST]) -> PATH: https://ngrok_url/api/v1/chat/iMessage;+;chat<number>/participant/remove
[BlueBubblesApp] [ERROR] (ERROR[500]) -> PATH: https://ngrok_url/api/v1/chat/iMessage;+;chat<number>/participant/remove
[BlueBubblesApp] [ERROR] (ERROR[500]) -> Http status error [500]
[BlueBubblesApp] [ERROR] (ERROR[500]) -> application/json; charset=utf/8
[BlueBubblesApp] [ERROR] (ERROR[500]) -> {status: 500, message: An unhandled error has occured!, error: {type: Server Error}}
```

The \<number> is replacing the actual chat number here since I'm typing this and didn't want to type the whole thing out. The same result occurs when switching the proxy service to cloudflare.

Been loving the app otherwise, thanks for being so active with this project!

**Comment by SprintKeyz** [comment]
Just saw the new helper bundle release, will test later today

**Comment by zlshames** [comment]
Im going to release a server update to address this
