### ISSUE TITLE
Images and videos not being sent properly on MacOS Montery

### ISSUE THREAD

**Issue by NotGrayFlamingo** [BlueBubblesApp/bluebubbles-server#415]
Images or videos that are sent from Bluebubbles with the server on MacOS Montery show as corrupted files to the recipient and on iMessage on the Mac.
![Screenshot_20220831-130047_Discord](https://user-images.githubusercontent.com/109780515/187946033-b9bc4ed8-9c43-4ed8-a165-eaab3a924002.jpg)
![Screenshot_20220831_140401](https://user-images.githubusercontent.com/109780515/187946081-ee424588-bd62-4ae1-9828-8b4f7f13d671.jpg)

**Comment by zlshames** [comment]
I've fixed this for the upcoming 1.3.0 release, hopefully today
