### ISSUE TITLE
Electron GPU Crashes

### ISSUE THREAD

**Issue by mehapps** [BlueBubblesApp/bluebubbles-server#418]
Ello @zlshames, making a ticket as requested.
Am having a white screen on startup, followed by a crash.
Am seeing it could possibly be symlink related, but turned off symlinks and still no dice.
`[1078:0902/200929.841477:ERROR:gpu_process_host.cc(979)] GPU process exited unexpectedly: exit_code=9
[1078:0902/200929.841505:FATAL:gpu_data_manager_impl_private.cc(448)] GPU process isn't usable. Goodbye.
zsh: trace trap  /Applications/BlueBubbles.app/Contents/MacOS/BlueBubbles

---@---HackBook-Pro ~ % [1142:0902/200929.917700:ERROR:mach_port_rendezvous.cc(310)] bootstrap_look_up com.BlueBubbles.BlueBubbles-Server.MachPortRendezvousServer.1: Permission denied (1100)
[1142:0902/200929.918778:ERROR:child_thread_impl.cc(228)] Mach rendezvous failed, terminating process (parent died?)`

**Comment by zlshames** [comment]
This is 100% an environmental issue. The only way to possibly fix it is to run the app with a flag to disable GPU rendering. However, I don't want to do this without lengthy testing. I'm closing this for now as it hasn't been reported by anyone else, and seems to be fixed by a macOS restore/reset
