### ISSUE TITLE
[Monterey, Private API] Messages sent as replies with subject line text and a space in the main body appear to not deliver/disappear

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-server#419]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#server-support`.

**Comment by zlshames** [comment]
I'm not able to reproduce this on Big Sur. Will need to do further testing on Monterey
