### ISSUE TITLE
Fix typo in connection setup

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-server#424]
https://github.com/BlueBubblesApp/bluebubbles-server/blob/master/packages/ui/src/app/layouts/walkthrough/connection/ConnectionWalkthrough.tsx#L36

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#general`.

**Comment by zlshames** [comment]
fixed
