### ISSUE TITLE
Option to not open window on startup

### ISSUE THREAD

**Issue by anonymousaga** [BlueBubblesApp/bluebubbles-server#426]
When I restart my mac or open it, the bluebubbles window relaunches. I'd like for an option to be there where when the program starts up, no window pops up the 1st time, so that it can be started on reboot without a window popping up. I am currently using the option to keep the dock icon visible. Thanks in advance.

**Comment by anonymousaga** [comment]
Thanks.

**Comment by zlshames** [comment]
The start minimized option has existed for quite some time. Closing
