### ISSUE TITLE
create option to auto lock mac after login startup

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-server#435]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@tneot01` in `#support`.

**Comment by zlshames** [comment]
Possibly detect startup by checking current uptime

**Comment by zlshames** [comment]
https://www.macobserver.com/tips/quick-tip/mac-system-uptime-terminal/

**Comment by zlshames** [comment]
There isn't really a good way to Lock your mac. Currently, the app uses osascript (AppleScript), but that can occassionally fail. This SO article suggests that there is a way using `pmset`, however, requires some additional configuring: https://apple.stackexchange.com/a/159440

**Comment by zlshames** [comment]
Figured it out using a Python script. Closing. Will be included in the next release
