### ISSUE TITLE
new messages with a delivered/read date already set do no get sent to the clients

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-server#447]

**Comment by zlshames** [comment]
This might be a client issue. With the changes I made recently, new messages should always arrive, and it may have a delivered timestamp attached. It might be getting ignored by the client

**Comment by tneotia** [comment]
I wonder if this is improved by the rowid checker

**Comment by zlshames** [comment]
I have a feeling it will help this

**Comment by zlshames** [comment]
Closing this for now since the server seems stable and we've not run into any issues with this
