### ISSUE TITLE
auto create Mac forge folders if base folder exists

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-server#454]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#general`.

**Comment by zlshames** [comment]
I believe I already do this: https://github.com/BlueBubblesApp/bluebubbles-server/blob/master/packages/server/src/server/services/privateApi/index.ts#L87

It auto-creates the plugins folder if the parent folder exists
