### ISSUE TITLE
Investigate how to improve group chat icon fetching

### ISSUE THREAD

**Issue by tneotia** [BlueBubblesApp/bluebubbles-server#482]
Referring to this code here: https://github.com/BlueBubblesApp/bluebubbles-server/blob/master/packages/server/src/server/databases/imessage/index.ts#L552

Couple things I'm noticing:

1. Is `cache_has_attachments` necessary? Maybe we just try to find the gc icon from the filesystem regardless of whether the db thinks its there or not.
2. We should probably not check against `group_action_type is 1`, rather `item_type is 3` and group_action_type is some int > 0

We may also investigate the chat table `properties` as that is a bplist, just to see what info is present inside, if its of any use.

**Comment by tneotia** [comment]
A few more things I'm noticing:

1. All group images are named GroupPhotoImage in the Attachments dir of /Library/Messages
2. Some of these images are not tied to a attachment GUID, but rather a chat itself:
<img width="404" alt="image" src="https://user-images.githubusercontent.com/50850142/215296706-0a3c9528-34e1-4247-aabb-da780ecb3f2f.png">
vs 
<img width="400" alt="image" src="https://user-images.githubusercontent.com/50850142/215296720-190b3ffb-6d76-44b9-9a2d-78fa624a3530.png">

In my Attachments dir, I have 5 images that are tied to an attachment GUID, and 3 tied to a chat GUID. When querying chat.db for attachments with the following code:
```sql
SELECT filename FROM attachment WHERE ROWID in (SELECT attachment_id FROM message_attachment_join WHERE message_id IN (SELECT ROWID FROM message WHERE item_type is 3 AND group_action_type > 0))
```
I only get the 5 images tied to the attachment GUID. So, one way to make the system better is to also search the Attachments dir for anything named `GroupPhotoImage` (if thats possible), and add the ones whos parent dir is a chat GUID (because the above query will not return those).

**Comment by zlshames** [comment]
Shouldn't be too hard I don't think.

1. Recursively get all file paths with the filename "GroupPhotoImage"
2. Match the chat GUID to the parent folder of the file.

One issue to think about is this. What if there is _both_ a chat GUID photo image AND a attachment record photo image? For instance if the image originally came from the iCloud sync, but later, it was changed. How do I know which one to use? I guess I can compare the file's created at date with the message's created at date.

But I'm just trying to figure out if that's possible or if it's either one or the other.

**Comment by tneotia** [comment]
I would probably use the one with the attachment record, I'd figure thats the more updated one. You can also compare the 2 files created at date and use the more recent one.

**Comment by tneotia** [comment]
I think I found a surefire way to get the proper GC image.
In the chat.db `chat` table, there's a bplist of `properties`. We can use the existing node-typedstream to parse this, and it appears to have a key called `groupPhotoGuid`. This points to an attachment GUID from which we subsequently get the path.

One interesting thing is that in some cases the attachment files aren't actually with extension for images, it has no extension. Adding .png to the end does open it properly though.

Sidenote: Maybe we should investigate the rest of the bplist as well, as it could contain some nice info.

**Comment by zlshames** [comment]
Done.
