### ISSUE TITLE
Export contacts function shows "request entity too large" in server logs and fails to export contacts

### ISSUE THREAD

**Issue by samir-a-ali** [BlueBubblesApp/bluebubbles-server#487]
[BlueBubbles-log-2023219_192748.txt](https://github.com/BlueBubblesApp/bluebubbles-server/files/10785673/BlueBubbles-log-2023219_192748.txt)
[main (1).log](https://github.com/BlueBubblesApp/bluebubbles-server/files/10785674/main.1.log)

**Comment by zlshames** [comment]
I'm going to increase the JSON size limit to hopefully solve this. Since idk what size the upload was, it's hard to know a number to use. It's currently 10mb, but im going to bump it to 100mb
