### ISSUE TITLE
[Feature Request] Send text captions together with attachments/send multiple attachments in one message

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/bluebubbles-server#491]
This is a dupe of [this ticket](https://github.com/BlueBubblesApp/bluebubbles-helper/issues/29#issuecomment-1445155306). My original caption and Tanay's response are quoted below.

> This is most notable when sending an attachment as a reply in the client app together with a text caption, but the text caption does not get included in the reply.

> This is already implemented but needs a server side API to actually be usable on the client. If you want, you can open an FR on server side just so zach doesn't forget.

Additionally, I was wondering if this could also apply for inserting attachments in between text parts of a message, like in [this comment from an AirMessage ticket](https://github.com/airmessage/airmessage-android/issues/3#issuecomment-832148751).

**Comment by tneotia** [comment]
endpoint added
