### ISSUE TITLE
Communicate with Private API to access digital touch and handwritten message media

### ISSUE THREAD

**Issue by carterashwood** [BlueBubblesApp/bluebubbles-server#492]
Would it be possible for the server to convert digital touch messages to a normal image format like gif or apng to be viewed on android? I suppose it's just a matter of figuring out how to read it on the server side (it may be an embedded image, but it's probably some custom proprietary thing knowing Apple).

**Comment by tneotia** [comment]
Its proprietary, and so far we have no idea what format it is in/how to decode it

**Comment by tneotia** [comment]
this has been figured out with the private api. I'm changing this ticket to focus on the server side communication aspect

**Comment by tneotia** [comment]
I would recommend creating a new endpoint like /message/<guid>/digital-touch-attachment and /message/<guid>/handwritten-attachment, with validation to make sure the provided message is actually a digital touch or handwritten. Then send the event to private API (`balloon-bundle-media-path` which needs `chatGuid` and `messageGuid`), which will return the path of the cached attachment.

**Comment by zlshames** [comment]
@tneotia what's the format of the transaction response object? or is it just a string to the file path?

**Comment by zlshames** [comment]
@tneotia also, are the output files GIFs? Or Movs?

**Comment by tneotia** [comment]
@zlshames yes string to file path, and for digital touch it is mov, for handwritten a png

**Comment by zlshames** [comment]
Done.
