### ISSUE TITLE
Add full Focus mode support

### ISSUE THREAD

**Issue by tneotia** [BlueBubblesApp/bluebubbles-server#498]
There's a handful of things we need to do on the server side:

### READ

There are 2 columns in chat.db which are relevant:
1. `was_delivered_quietly` (0 or 1) to indicate that a text was delivered quietly due to a user's focus mode. This is likely set once `date_delivered` is also set.
2. `did_notify_recipient` (0 or 1) to indicate that a text was forcefully notified (overriding the recipient's focus mode). We will need a DB listener for this, because the user can change this value anytime they want.

To read the other user's focus mode state, use private API method `check-focus-status`, which needs address (similar to add/remove participant). Returns `transactionId` and `silenced` (0 or 1).

### WRITE

This will be called from the apps by users who wish to override the recipient's focus mode. Use private API method `notify-anyways`, which needs `chatGuid` and `messageGuid`. Once this method is complete, the aforementioned `did_notify_recipient` column should change to a 1.

**Note: This supersedes #497 **

**Comment by zlshames** [comment]
@tneotia Should I make these fields hidden for notifications to not bloat the notification? i assume they arent required really.

**Comment by zlshames** [comment]
Ok, they'll be included in the API, just not notifications

**Comment by tneotia** [comment]
Can you also include them in update-message events

**Comment by zlshames** [comment]
> Can you also include them in update-message events

when you say events, do you mean socket events or notifications?

**Comment by zlshames** [comment]
Done.
