### ISSUE TITLE
Server (1.6.0) Crashes Immediately Upon Execution - El Capitan 10.11.6

### ISSUE THREAD

**Issue by kurtwickboldt** [BlueBubblesApp/bluebubbles-server#508]
Bluebubbles server throws the following error upon executing on El Capitan 10.11.6, even though release 10.5.5 works fine.

![Screen Shot 2023-03-28 at 9 05 06 AM](https://user-images.githubusercontent.com/102988141/228265839-ab7e0098-da15-4474-b9a9-537643b5bfe8.png)

**Comment by zlshames** [comment]
this permissions plugin will be the death of me... works on Ventura, but not Big Sur... Works on both big Sur and Ventura, but not El Capitan...

Any chance you can upgrade to high sierra?

**Comment by zlshames** [comment]
> Unfortunately I'm on a mid 2009 MBP so I can't upgrade past the latest/last version of El Capitan :( I did see the release note of downgrading the node-mac-permissions but I haven't had a chance to look into how to do that yet.

Yeah, so that note is if you want to manually build it yourself. But it seems like with that dependency upgrade, it lost support for El Capitan... supporting an 8 year old operating system is hard. The problem is, idk if there is a comparable library that'll work properly with El Capitan.

**Comment by kurtwickboldt** [comment]
Ah I see, in that case I can stick with 1.5.5 for the time being then. I'm curious if El Capitan will be supported in future releases since a lot of the older machines are useful for running the server. I can also take the VM route if need be. Either way I appreciate the development!

**Comment by kurtwickboldt** [comment]
Upgrading to High Sierra from El Capitan fixed this issue. Followed the upgrade guide from http://dosdude1.com/highsierra/
