### ISSUE TITLE
[1.7.0] No advanced connection settings

### ISSUE THREAD

**Issue by topiga** [BlueBubblesApp/bluebubbles-server#511]
This might be a bug, I don't need it, but the advanced connection settings are empty :
![Capture d’écran 2023-03-31 à 22 02 46](https://user-images.githubusercontent.com/38886040/229218796-9436e2ee-210f-4bce-b9c3-a407fb11ea24.png)

**Comment by zlshames** [comment]
Done.

**Comment by zlshames** [comment]
It was because i removed the encrypt coms setting, and the only other setting in it only showed if dynamic dns was selected
