### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by BlueOutside** [BlueBubblesApp/bluebubbles-server#532]
Im on El Capitan and i was about to try bluebubbles but when i started the app i get A JavaScript error occurred in the main process with this
Uncaught Exception:
Error: dlopen(/Applications/BlueBubbles.app/Contents/Resources/app.asar.unpacked/node_modules/node-mac-permissions/build/Release/permissions.node, 1): Symbol not found: _OBJC_CLASS_$_PHPhotoLibrary
  Referenced from: /Applications/BlueBubbles.app/Contents/Resources/app.asar.unpacked/node_modules/node-mac-permissions/build/Release/permissions.node (which was built for Mac OS X 10.13)
  Expected in: /System/Library/Frameworks/Photos.framework/Versions/A/Photos
 in /Applications/BlueBubbles.app/Contents/Resources/app.asar.unpacked/node_modules/node-mac-permissions/build/Release/permissions.node
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/Applications/BlueBubbles.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/Applications/BlueBubbles.app/Contents/Resources/app.asar/node_modules/node-mac-permissions/index.js:1:40)

**Comment by zlshames** [comment]
Are you on an OpenCore deployment of macOS? I assume Monterey or newer?

**Comment by BlueOutside** [comment]
On another partition yes but it's APFS

**Comment by ksulaimon** [comment]
I have this same issue trying to open bluebubbles on a Mac mini running El Capitan... Any updates here?

**Comment by zlshames** [comment]
> I have this same issue trying to open bluebubbles on a Mac mini running El Capitan... Any updates here?

I would advise upgrading to newer than El Capitan. I think the APIs we use to support newer features just aren't compatible with El Capitan. And i think I need to phase out support for it. It doesnt seem to work properly with it either because of those low-level API changes.

**Comment by BlueOutside** [comment]
> > I have this same issue trying to open bluebubbles on a Mac mini running El Capitan... Any updates here?
> 
> I would advise upgrading to newer than El Capitan. I think the APIs we use to support newer features just aren't compatible with El Capitan. And i think I need to phase out support for it. It doesnt seem to work properly with it either because of those low-level API changes.

So i would but... the macbook im using doesn't support macOS Sierra+ and it's a bit slow when i use dosdude1 ctlna patcher

**Comment by zlshames** [comment]
> > > I have this same issue trying to open bluebubbles on a Mac mini running El Capitan... Any updates here?
> > 
> > 
> > I would advise upgrading to newer than El Capitan. I think the APIs we use to support newer features just aren't compatible with El Capitan. And i think I need to phase out support for it. It doesnt seem to work properly with it either because of those low-level API changes.
> 
> So i would but... the macbook im using doesn't support macOS Sierra+ and it's a bit slow when i use dosdude1 High Sierra patcher

While it might feel slow in usage, it probably works just fine for BB if that's all you use it for. That said, Im not sure what to do about this since the APIs aren't compatible anymore. The only way to get around it would be to manually build the server without the `node-mac-permissions dependency

**Comment by zlshames** [comment]
Would you guys (@BlueOutside @ksulaimon ) like to try a test version of the server where I've attempted to fix this issue on El Capitan? If so, please DM me in the Discord.

**Comment by BlueOutside** [comment]
> Would you guys (@BlueOutside @ksulaimon ) like to try a test version of the server where I've attempted to fix this issue on El Capitan? If so, please DM me in the Discord.

Okay ima try it later this week im going to send u a DM on discord soon
