### ISSUE TITLE
New conversation creations seem to fail with weird error (non-iMessage number)

### ISSUE THREAD

**Issue by lfaraone** [BlueBubblesApp/bluebubbles-server#533]
Server version: 1.7.2 
Android version: 1.12.2
macOS 13.3.1 (a) (22E772610a)
Locale: en_GB

Any time I create a new conversation, I get this error: 

In server side logs: `syntax error: Expected end of line but found property. (-2741)` or (in the fallback) `Expected class name but found identifier. (-2741)`.

I believe this bug has been present since I started using BlueBubbles a few months ago. 

![Screenshot (14 May 2023 17:46:32)](https://github.com/BlueBubblesApp/bluebubbles-server/assets/73410/76afa76b-6b48-4812-875c-46d61a563375)

Server-side logs: 
[bluebubbles_log_20230514.log](https://github.com/BlueBubblesApp/bluebubbles-server/files/11473327/bluebubbles_log_20230514.log)

**Comment by lfaraone** [comment]
Granted, in this case, the message sending did fail, it wasn't an iMessage number: 
<img width="295" alt="image" src="https://github.com/BlueBubblesApp/bluebubbles-server/assets/73410/cc827496-843c-4c32-b2ca-fe7455536b65">

**Comment by zlshames** [comment]
Hmmm, this one is baffling to me, and might be induced by an update by Apple. Are you on a physical mac or virtual? I copied the same code to my editor and it executed just find, just with a different number

**Comment by zlshames** [comment]
Closed because it was a bug in the macOS environment
