### ISSUE TITLE
FaceTime server issue and feature request 

### ISSUE THREAD

**Issue by CompuGenius** [BlueBubblesApp/bluebubbles-server#539]
Issue: In the server, I get `Failed to start FaceTime server... osascript can't open default scripting component`.
I'm running on MacOS Monterey (12.6.5) through VMWare.

Feature request: I haven't seen it mentioned in any PRs or issues, but I know Airmessage has a (somewhat working) feature where their app automatically converts FaceTime calls to FaceTime links that their client apps can then handle. Would this be a possible feature to add to BlueBubblesApp?

**Comment by zlshames** [comment]
@CompuGenius we still don't technically know why this happens. We are just running AppleScripts, which should theoretically be fine, but we've seen this issue before. There is no fix to it outside of rebooting your Mac. And we suggest to disable the Facetime detection feature right after so it doesn't happen again.

We will be looking into ways to mitigate this. Or even improve upon it using the Private API.

**Comment by CompuGenius** [comment]
> There is no fix to it outside of rebooting your Mac.

I have noticed that if I reboot, the error stops for a bit, but does always come back. Oh well 🤷‍♂️

Do you have any plans regarding the Facetime link integration itself?

**Comment by zlshames** [comment]
> > There is no fix to it outside of rebooting your Mac.
> 
> I have noticed that if I reboot, the error stops for a bit, but does always come back. Oh well 🤷‍♂️
> 
> Do you have any plans regarding the Facetime link integration itself?

I think we are more likely to try and accomplish it through the Private API to make it more reliable than using UI scripting using Accessibility.

Also, for what it's worth, we've compared our AppleScript code to AirMessage's and they seem very very similar, and essentially do the same thing. We are not sure why it would cause a persistent issue, but not for AirMessage.

**Comment by CompuGenius** [comment]
> I think we are more likely to try and accomplish it through the Private API to make it more reliable than using UI scripting using Accessibility.

Awesome, I use Private API so that's great! I happen to be an experienced developer and am pretty passionate about this, so I'd actually be happy to go through and try to learn what's happening with this entire project so I can help add the facetime functionality, if needed.

**Comment by zlshames** [comment]
> > I think we are more likely to try and accomplish it through the Private API to make it more reliable than using UI scripting using Accessibility.
> 
> Awesome, I use Private API so that's great! I happen to be an experienced developer and am pretty passionate about this, so I'd actually be happy to go through and try to learn what's happening with this entire project so I can help add the facetime functionality, if needed.

If you join our discord, we have channels dedicated to this type of collaboration. So feel free to chime in and give us a shout!

**Comment by zlshames** [comment]
I'm closing this as we will very soon be removing the ability to get the FaceTime status via AppleScript, in favor of doing it via the Private API on Big Sur and newer. The FaceTime detection via the AppleScript compromised the stability of the server and I'm glad we were able to replace it using the Private API.
