### ISSUE TITLE
Sign in error (cannot read properties of null (reading 'client')...)

### ISSUE THREAD

**Issue by nep2ner** [BlueBubblesApp/bluebubbles-server#543]
Android App Version: 1.12.2
Server Version: 1.7.3

---
When I try to connect to BlueBubbles I get this issue. Does anyone have any ideas? I've had it working before. I connect to BlueBubbles by connecting directly to my IP address, then to nginx reverse proxy for ssl encryption, then on to the mac for blue bubbles. I've double checked that the password is correct, so I don't think that is the issue.

---

Server Log (debug checked):
```
TypeError: Cannot read properties of null (reading 'client') at getClientConfig (/Applications/BlueBubbles.app/Contents/Resources/app.asar/dist/main.js:1:171081) at dispatch (/Applications/BlueBubbles.app/Contents/Resources/app.asar/node_modules/koa-compose/index.js:42:32) at Jl (/Applications/BlueBubbles.app/Contents/Resources/app.asar/dist/main.js:1:87527) at dispatch (/Applications/BlueBubbles.app/Contents/Resources/app.asar/node_modules/koa-compose/index.js:42:32) at ld (/Applications/BlueBubbles.app/Contents/Resources/app.asar/dist/main.js:1:178511) at dispatch (/Applications/BlueBubbles.app/Contents/Resources/app.asar/node_modules/koa-compose/index.js:42:32) at cd (/Applications/BlueBubbles.app/Contents/Resources/app.asar/dist/main.js:1:178891) at dispatch (/Applications/BlueBubbles.app/Contents/Resources/app.asar/node_modules/koa-compose/index.js:42:32) at gd (/Applications/BlueBubbles.app/Contents/Resources/app.asar/dist/main.js:1:179270) at dispatch (/Applications/BlueBubbles.app/Contents/Resources/app.asar/node_modules/koa-compose/index.js:42:32)
```

![server-debug](https://github.com/BlueBubblesApp/bluebubbles-server/assets/86129988/23ab8c58-8905-40fb-851e-f345309e5812)

Android App
![android](https://github.com/BlueBubblesApp/bluebubbles-server/assets/86129988/80db214d-d1a2-417f-8f23-898102a5685f)

**Comment by zlshames** [comment]
@nep2ner This says to me that the Google FCM files were not quite setup properly. Did you download and load your 2 Google Firebase JSON files into the server?

**Comment by nep2ner** [comment]
> @nep2ner This says to me that the Google FCM files were not quite setup properly. Did you download and load your 2 Google Firebase JSON files into the server?
> 
> Also, I think the error is fixed in my latest beta. You probably aren't on it. Just know that the error you are seeing has been addressed.

I forgot to mention that I am running this with no Google FCM. I have been using it with the websocket notifications.

You are correct when you say I am not on the beta. I will try to connect again after the next update and see if it is fixed. How can I know when the next update comes?
