### ISSUE TITLE
Messages with multiple attachments will only return one of the attachments

### ISSUE THREAD

**Issue by tnvu** [BlueBubblesApp/bluebubbles-server#547]
I think I found the issue --

MessageRepository.getAttachment() accepts an attachment GUID but discards the attachment prefix to perform a lookup based on the "actual" guid. It then queries the database and then calls query.getOne() which return the same attachment every single time.

**Comment by zlshames** [comment]
Moved. I'll fix it

**Comment by tnvu** [comment]
Thanks. I submitted a possible solution here

https://github.com/BlueBubblesApp/bluebubbles-server/pull/546

I haven't tested it yet because I can't get things to build on my system.

**Comment by zlshames** [comment]
PR merged. Should be good now. Hard to officially test, but it was working normally

**Comment by tnvu** [comment]
You can test by sending a message with multiple attachments. It should
return individual images and not the same image multiple times

**Comment by zlshames** [comment]
The issue was not fixed. And I think the changes broke something more than I thought. Gonna have to revert some of the code and retry it

**Comment by zlshames** [comment]
Fixed again. It's cuz the for loop used "in" instead of "of" and it caused the list of GUIDs to improperly be iterated over. It was iterating over the indexes, not the values. 

Just JavaScript things 😁
