### ISSUE TITLE
Server App Cannot Login with Google - Disabled Client

### ISSUE THREAD

**Issue by ranajay5699** [BlueBubblesApp/bluebubbles-server#549]
Says there is a disabled client see attached image for more details. I am using the beta server app. 
![Screenshot 2023-07-08 at 4 45 22 PM](https://github.com/BlueBubblesApp/bluebubbles-server/assets/9078106/91ccd8dd-31ef-4039-9131-755327499dab)

**Comment by zlshames** [comment]
This is a known issue and is due to our "app" not being verified yet by Google. As such, we have a 100 user sign up limit. we are hoping to remediate this issue by "appealing" Google's initial denial verdict due to using too sensitive scopes. We are awaiting their response.

**Comment by ranajay5699** [comment]
Awesome, glad you're aware already, thank you!!

**Comment by zlshames** [comment]
Fixed & verified by Google now :)
