### ISSUE TITLE
Support ngrok static domains

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-server#569]

**Comment by Rihcus** [comment]
https://ngrok.com/blog-post/free-static-domains-ngrok-users?utm_campaign=Monthly%20Newsletter&utm_medium=email&_hsmi=273371496&utm_content=273371496&utm_source=hs_email

**Comment by zlshames** [comment]
Closing. You should be able to do this via the default ngrok config file that lives on the mac. BlueBubbles should use it. https://ngrok.com/docs/agent/config/

**Comment by zlshames** [comment]
Done on my development branch
