### ISSUE TITLE
Fix out of order chats on some clients

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-server#570]
Maybe auto sort by last message (without sort param) when last message is requested. 

We can't reproduce the ordering issue, unfortunately

**Comment by seanlowe** [comment]
This is especially present on the android mobile client. I send messages and they will shuffle themselves around out of order. This translates to the linux desktop app when the messages originate from the mobile app. If I send messages from the desktop app they send and receive in order.

**Comment by zlshames** [comment]
> This is especially present on the android mobile client. I send messages and they will shuffle themselves around out of order. This translates to the linux desktop app when the messages originate from the mobile app. If I send messages from the desktop app they send and receive in order.

I think the ticket is actually for something different. The issue in this ticket is that the Chats are not in order (though, they should be). Your issue is that your messages shuffle. The message shuffling issue might be because the time/timezone on your mac is not synced with the time servers. Either that, or your phone's time isn't synced properly. You can go to https://time.is on your mac and/or phone to see if your time is "off" by a significant amount

**Comment by zlshames** [comment]
Closing as im not sure this is still an issue, or even an issue that the server can account for
