### ISSUE TITLE
Change default area code

### ISSUE THREAD

**Issue by Radiicall** [BlueBubblesApp/bluebubbles-server#572]
When i send messages to my contacts who dont have area codes it adds +1 to them, which doesnt really work when the area code for Norway is +47, i couldnt see any issues mentioning this so i might just be missing something... I did however see #534 where it looks like this got implemented in the first place.

It would be great if the default area code could be changed for users living outside the US

**Comment by zlshames** [comment]
Here is how the server works:

1. If a country code is provided with the address when creating a chat, it will use that country code.
2. If a country code is _not_ provided, the server will use the country code associated with the selected region for the Mac
3. If either #1 or #2 don't hit, it defaults to +1

Here is the associated code: https://github.com/BlueBubblesApp/bluebubbles-server/blob/master/packages/server/src/server/helpers/utils.ts#L82-L94

What we _really_ need to do is force the client to choose a country code, if none is provided. Closing this as it's more of a client change than anything. Unless you see something wrong with the logic above. If so, I can reopen this
