### ISSUE TITLE
Mac Server Application doesn't function

### ISSUE THREAD

**Issue by winteriscariot** [BlueBubblesApp/bluebubbles-server#577]
I downloaded the DMG from the Releases page (1.8.0 as of this writing) and installed it on my 2017 i5 MBP. when I launched the app I was presented with a blank white window.

Looking through some responses both here and on reddit, I went ahead and totally wiped and reinstalled MacOS on this machine (I literally only use it for iMessage so this wasn't a big deal).

However, the issue persists.

The menu bar icon appears when the application is launched, and there is information there. This includes what appears to a randomly generated 'trycloudflare.com' subdomain link. When I go to that link I get a generic message: "Welcome to the BlueBubbles Server landing page!" But ofc i can't configure the server cuz the UI never loads.

Upon investigating this in Console.app I notice that the BlueBubblesServer Helper is crashing. This is consistent with the fact that upon launching the BlueBubblesServer application my CPU spikes and CrashReport starts using well over 100% CPU. The console shoes that this helper process is in a crash loop.

Is there anything I can do about this? Again, this is a freshly installed MacBook Pro.

Thanks!

**Comment by Kasherpete** [comment]
I'm no expert, but I do believe this is that one Electron issue others have been having with the server. More on that [here](https://discord.com/channels/640229510662455326/782690923640782878/1166145221965393920).

**Comment by winteriscariot** [comment]
> I'm no expert, but I do believe this is that one Electron issue others have been having with the server. More on that [here](https://discord.com/channels/640229510662455326/782690923640782878/1166145221965393920).

Thank you! Someone in that channel had a solution: Had to disable the 'ipc_control_port_options' NVRAM boot arg. So the following command (and reboot) fixed it:

    nvram boot-args "$(nvram boot-args) ipc_control_port_options=0"
