### ISSUE TITLE
FR: Sync with Google Contacts

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-server#578]

**Comment by raddacle** [comment]
You can sync them by adding your Google account to MacOS's system settings.

**Comment by zlshames** [comment]
> You can sync them by adding your Google account to MacOS's system settings.

Good point, but some users have reported that avatars don't sync properly. And since we have the login with Google thing, it makes it kinda easy to also grab contacts or something

**Comment by AndyXheli** [comment]
Yes I would agree the pictures don't sync over from google also it would be cool If the profile photo sync across all devices and maybe grab the main Google photo profile over ?

**Comment by zlshames** [comment]
> Yes I would agree the pictures don't sync over from google also it would be cool If the profile photo sync across all devices and maybe grab the main Google photo profile over ?

yes, we have thought about pulling that info since BlueBubbles already asks for access to your google account for setting up firebase. I just need to implement it. That would likely be the best way to go, rather than using the Google sync via the Contacts app

**Comment by tchirou** [comment]
Hi. I stumbled on this problem today and I have found that I had some pictures in the windows client if the google contact hadn't any space in the cell number. For the contacts registered with spaces, no pictures in the client. Weirdly, even if I change it and reset settings in the server and clients apps, I can't get the picture. I even thrwon the server out of applications into the bin, but when I installed it again, the settings were still there. I am a noob on macos, so I don't know how to properly ininstall, I have check in Apllication support and did a search but nothing.

**Comment by mstras** [comment]
I Would love to see direct google contacts integration. This would definitely end a lot of the contact issues with it syncing from the mac contacts app.

**Comment by mstras** [comment]
Would it be possible to set an interval when it pulls. Such as daily, weekly, etc instead of just when a user manually hits the button?

**Comment by zlshames** [comment]
> Would it be possible to set an interval when it pulls. Such as daily, weekly, etc instead of just when a user manually hits the button?

Unfortunately, no, not without a server to handle the persistent authentication, or not without including the client secret in the source code (which we don't want to do). This is because when you authenticate, the credentials are only valid for 30 minutes or so. Whatever the default time is. If I try to use the credentials 24 hrs later, it won't work until you consent again
