### ISSUE TITLE
Sending two messages since server 1.9.0

### ISSUE THREAD

**Issue by levogevo** [BlueBubblesApp/bluebubbles-server#582]
BlueBubbles is suddenly sending two messages per chat since the 1.9.0 update.
-Server version: 1.9.0
-macOs Version: 13.4.1
-Proxy service: dynamic dns
-Using Private API

**Comment by levogevo** [comment]
With some additional testing, seems that turning off private api send resolves the issue. However, this should not be the case. seems like a bug with `1.9.0` server

**Comment by zlshames** [comment]
@levogevo when this occurs, are there multiple Messages apps running?

**Comment by levogevo** [comment]
> @levogevo when this occurs, are there multiple Messages apps running?

No. I tried resetting the machine, restarting the machine, restarting bluebubbles only, restarting messages only. I can confirm that turning off Private API send resolves the issue and turning it back on immediately results in double messages again. It seems to be directly tied to Private API send

**Comment by zlshames** [comment]
Can you join our discord and ping me? I have a test build I'd like you to try to fix the issue.

**Comment by jpcamp** [comment]
I disabled MacForge (Didn't realize it wasn't necessary after 1.8+) and that did the trick.

**Comment by levogevo** [comment]
> I disabled MacForge (Didn't realize it wasn't necessary after 1.8+) and that did the trick.

Yea I figured that out with the help of zlshames a few days ago, forgot to close this issue.
