### ISSUE TITLE
Multiple Servers

### ISSUE THREAD

**Issue by raddacle** [BlueBubblesApp/bluebubbles-server#583]
Is it possible for to have multiple instances of the server to sustain a connection even if one server goes down? 

For instance, having one server instance at your own home and another at family member's house, both with the same account details. If there is a power or internet outage at one of those sites, your phone can connect to the other.

**Comment by zlshames** [comment]
No because the iMessage database IDs are not consistent across different Mac servers. So an ID for one chat will be completely different on another Mac. For that reason, we can't do this

**Comment by raddacle** [comment]
Ah that makes sense. Would it be feasible to have something like regex matching of the contact and some messages to connect the IDs between Macs in a database? 

I'm new to bluebubble (which has been really great), and I'd like to feel like I could trust it to always be up to date and not reliant on a single home setup having no downtime.

**Comment by zlshames** [comment]
> I've had this thought, too and have considered running a backup BB server on an old Mini. In theory, couldn't you just reconnect the client to the backup server? It wouldn't be a seamless failover, as it'd have to re-sync, so maybe you'd only have a week of messages (or whatever duration you're comfortable pulling down), but in effect it would be just like setting up a brand-new BB server. Creates a bit of manual work but still seems like a good backup option if you're traveling or otherwise away from home for a while.
> 
> Am I thinking about that right?

Hmmmm, I'm not totally sure. I would assume it would need to basically be an exact copy of your original mac? Or maybe it only needs to have the same starting DB? I'm not sure. It would require pretty extensive research to figure out I'd imagine.

**Comment by zlshames** [comment]
> Ah that makes sense. Would it be feasible to have something like regex matching of the contact and some messages to connect the IDs between Macs in a database?
> 
> I'm new to bluebubble (which has been really great), and I'd like to feel like I could trust it to always be up to date and not reliant on a single home setup having no downtime.

Nahh, it's just a random GUID that's assigned to messages, chats, attachments, etc. And none of them "match" across servers
