### ISSUE TITLE
Facetime auto-opening, cannot close on Mac with BlueBubbles Server

### ISSUE THREAD

**Issue by dgithubg** [BlueBubblesApp/bluebubbles-server#585]
With the Private API enabled, there Facetime now automatically opens when Bluebubbles Server is running. 
Closing Facetime causes it to immediately re-open, as long as BB Server is running. 

Closing BB Server allows me to close Facetime without it re-opening. 

I would like to keep Facetime off, but still have access to the Private API features (that do not rely on Facetime).

**Comment by aikiharp** [comment]
Having the same issue. Because FaceTime is open, my camera is always running; I noticed it last night. I would prefer to avoid this. Is there a setting in the server or app that disables FaceTime monitoring? And what does FaceTime monitoring do on Android?

**Comment by zlshames** [comment]
If you guys join our Discord and ping me i will/can send you a pre-release for the next version so you guys can help test the changes I made to fix the issue you are having
