### ISSUE TITLE
Auto close contacts app in order to fix contacts not being sent to client

### ISSUE THREAD

**Issue by maxwellfortney** [BlueBubblesApp/BlueBubbles-Server#59]

**Comment by zlshames** [comment]
I actually want to make fetching contacts not automatic. Aka, I think we should add a tab to the config of the desktop app to allow the updating of contacts via a button. 

That way, we can let the user choose which method to get the contacts from: local vcf, server vcf, or server database

**Comment by zlshames** [comment]
You may want to make tickets for that on the desktop app project @maxwellfortney

**Comment by zlshames** [comment]
My branch
