### ISSUE TITLE
New Server URL not coming in webhook

### ISSUE THREAD

**Issue by goodsoftwaredev** [BlueBubblesApp/bluebubbles-server#591]
Using version 1.8.0

The webhook is working for other events, but the new server url event has stopped working

**Comment by goodsoftwaredev** [comment]
Just get the hello world when the proxy server restarts and Cloudflare issues a new url

**Comment by burntoc** [comment]
Any workaround we can use in the interim?

**Comment by zlshames** [comment]
> Any workaround we can use in the interim?

This should be fixed in the latest release. If you are still having issues, please check out your server log file to get the actual error being generated when the webhook fails.
