### ISSUE TITLE
Read columns relating to location share status and direction

### ISSUE THREAD

**Issue by SpaceSaver** [BlueBubblesApp/bluebubbles-server#594]
@tneotia Told me to mention this here.  This relates to this issue in the app: https://github.com/BlueBubblesApp/bluebubbles-app/issues/2598.  The reason the app is unable to distinguish between location being shared, and stopping being shared is because the share_status and share_direction columns need to be read from the server.

**Comment by zlshames** [comment]
Done, dev branch
