### ISSUE TITLE
feat: Voice Note transcripts

### ISSUE THREAD

**Issue by CompuGenius-Programs** [BlueBubblesApp/bluebubbles-server#596]
On my Messages app, I see auto-generated transcripts for voice notes. It would be amazing if this could be added to the app.
Thank you!

**Comment by cameronaaron** [comment]
Hey this should be probably be in the app repo not here

**Comment by CompuGenius-Programs** [comment]
> Hey this should be probably be in the app repo not here

It's quite literally a server-side feature.
Besides the fact that it's Messages itself that transcribes the voice notes, even if I was requesting BB to code it themselves, it would still be server side.

**Comment by zlshames** [comment]
What Mac OS version was transcripts introduced in? There is a chance that we already have that data available within the attributed body or message summary info. Testing it might be the trickier part. If the feature is not available on Mac OS and only iOS, then it will need to be a client-side feature. Unless I implement processing on the server to do it

**Comment by CompuGenius-Programs** [comment]
> What Mac OS version was transcripts introduced in? There is a chance that we already have that data available within the attributed body or message summary info. Testing it might be the trickier part. If the feature is not available on Mac OS and only iOS, then it will need to be a client-side feature. Unless I implement processing on the server to do it

It's definitely available on MacOS (I don't have an iPhone), I just don't know what version it was introduced in

**Comment by zlshames** [comment]
We've figured out where the data lies. This will now be an app FR: https://github.com/BlueBubblesApp/bluebubbles-app/issues/2762
