### ISSUE TITLE
Attachments fail to send

### ISSUE THREAD

**Issue by binex-dsk** [BlueBubblesApp/bluebubbles-server#600]
Running on macOS Sonoma on the latest version. Images fail to send from the app, no details are given by the app.

**Comment by SpaceSaver** [comment]
Private API or regular?

**Comment by binex-dsk** [comment]
I have the Private API enabled if that's what you're asking.

**Comment by zlshames** [comment]
> I have the Private API enabled if that's what you're asking.

Are you Abel to send images from the native iMessage app on your Mac?

**Comment by binex-dsk** [comment]
> > I have the Private API enabled if that's what you're asking.
> 
> Are you Abel to send images from the native iMessage app on your Mac?

No, interestingly, everything sent from the phone and Mac shows up on my end, but not on the receiving end.

Additionally, attachments are rreceived just fine on the Mac side but not by the phone.

**Comment by binex-dsk** [comment]
Here are what the logs look like:

![1000002047.jpg](https://github.com/BlueBubblesApp/bluebubbles-server/assets/65276418/c753df95-da70-4035-82fd-6ede630f1a69)

Interestingly, it seems the attachment is sent but then a message is sent with no text in its stead. Here's what it looks like on the Mac side when sent from the phone:

![1000002048.jpg](https://github.com/BlueBubblesApp/bluebubbles-server/assets/65276418/4556d40c-cff9-415a-8567-98f5be698b9c)

and from the Mac:

![1000002050.jpg](https://github.com/BlueBubblesApp/bluebubbles-server/assets/65276418/d9e58e98-107a-4b47-b108-7bdd25cf85f8)



Here's what it all looks like from the receiving end:

![1000002051.jpg](https://github.com/BlueBubblesApp/bluebubbles-server/assets/65276418/d95874e3-5bcc-415a-bfa3-82c8f93aa3e9)


a blank text.

**Comment by binex-dsk** [comment]
Sending attachments with text results in the text being destroyed, including on the Mac side, with logs looking identical

**Comment by binex-dsk** [comment]
Actually, the text itself is sent later, with the blank message sent well before, then a long lag and the text is sent. When done from the Mac, it results in the text being liquidated and the entire image and text replaced by a blank text.

**Comment by zlshames** [comment]
> > > I have the Private API enabled if that's what you're asking.
> > 
> > 
> > Are you Abel to send images from the native iMessage app on your Mac?
> 
> No, interestingly, everything sent from the phone and Mac shows up on my end, but not on the receiving end.
> 
> Additionally, attachments are rreceived just fine on the Mac side but not by the phone.

Unfortunately, if you are unable to send attachments/images from the Mac, BlueBubbles will also be unable to send attachments/images. This may indicate a faulty macOS installation, or maybe a block on the iMessage side of things, connecting to your iCloud account. You can try to call Apple support (or chat) to see if they can help.

**Comment by zlshames** [comment]
Mac issue. Closing

**Comment by binex-dsk** [comment]
Apple Support has been unhelpful. Probably cuz I used beeper mini 🥶

**Comment by SpaceSaver** [comment]
> Apple Support has been unhelpful. Probably cuz I used beeper mini 🥶

Did you tell them that?

**Comment by binex-dsk** [comment]
No, but I've faced issue with Apple ID since I started using it.
