### ISSUE TITLE
Look into dispatch error

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-server#605]
The only log message was `Failed to handle server address change! cannot read properties of null (reading 'dispatch')`

**Comment by srishChicago** [comment]
I have get this error every time the BlueBubbles v1.9.4 server is restarted after Reset App and default settings. Using Cloudflare proxy & password

Server info:
MacMini (late 2012 2.5 GHz Dual-Core Intel Core i5)
MacOS: Sonoma 14.3 via OpenCore 1.3.0
Full disk access and accessibility granted

**Comment by zlshames** [comment]
> I have get this error every time the BlueBubbles v1.9.4 server is restarted after Reset App and default settings. Using Cloudflare proxy & password
> 
> Server info: MacMini (late 2012 2.5 GHz Dual-Core Intel Core i5) MacOS: Sonoma 14.3 via OpenCore 1.3.0 Full disk access and accessibility granted
> 
> Error: Failed to handle server address change! cannot read properties of null (reading 'dispatch')

This is fixed in the upcoming 1.9.5 update
