### ISSUE TITLE
Doc issue for server install: Firebase info

### ISSUE THREAD

**Issue by weflower** [BlueBubblesApp/bluebubbles-server#606]
Hi,

When I was setting up BlueBubbles server app and the client app, I noticed an issue that I think could be mentioned in the documentation.

There's a few steps in the Firebase setup that are not described in the setup instructions here:  
https://bluebubbles.app/install/

The instructions currently read:

> Proceed through the Intro, and Permissions steps, following the on-screen guide to enable accessibility and full disk access. Note that accessiblity is not required for BlueBubbles to function.
> 
 > Once full disk access is enabled, proceed to the Notifications step. Connect your Google account so we can provision a Firebase project for notifications.
 > [missing]
 > Wait for the project creation to finish, as indicated in the logs below.

What actually happens in the [missing] section is:
1. a webview pop-up appears that goes to the Firebase home page (with your account already signed in).
2. Click **Create a project**.
3. Click in the name field and select the existing "BlueBubbles" project.
4. Click through the menus, modify any settings if you need, and complete the Firebase setup.

Then the app is able to connect. On the client side, you must restart the client app if you have it already open and re-authenticate with Google. Otherwise the client app will not notice the new/working connection.

**Comment by weflower** [comment]
split client info into separate issue in client repo

**Comment by zlshames** [comment]
Fixed. Thanks. 
![image](https://github.com/BlueBubblesApp/bluebubbles-server/assets/18445938/0a16e48e-219e-4e08-8013-0093eb58edf2)
