### ISSUE TITLE
Server unable to request Contacts permission from macOS 14.3

### ISSUE THREAD

**Issue by bobbyl140** [BlueBubblesApp/bluebubbles-server#612]
I installed yesterday, and while trying to get everything setup, I clicked `Request Permission` on the Contacts tab, but all that does is open Privacy & Security settings. macOS never asks me to allow/deny, and since the Contacts section in settings doesn't let you manually add apps, I can't get it to work, as the server remains saying "Denied".

My temporary solution is to export my entire contacts database as a file, and import it myself, but this has two shortcomings: no contact photos, and no automatic updates.

**Comment by zlshames** [comment]
Hey, have you tried this solution? https://discord.com/channels/640229510662455326/782690923640782878/1161015289471828028

Essentially, you may need to modify the tcc DB to get it to show up. I think it is a quirk with OpenCore

**Comment by bobbyl140** [comment]
Well I didn't even think about OpenCore, I'm amazed that you know I'm using that! But I'll see what I can do about TCC.

**Comment by bobbyl140** [comment]
Would you actually tell me what server that's in? I can't view it without being a part of the server it seems.

**Comment by zlshames** [comment]
> Would you actually tell me what server that's in? I can't view it without being a part of the server it seems.

It's the BlueBubbles Discord: https://discord.gg/hFgbV8Jank

**Comment by bobbyl140** [comment]
Well I tried a few solutions of editing TCC, all output success, but none of them have updated System Settings or BlueBubbles even after multiple reboots. Sounds like a macOS bug now...

**Comment by bobbyl140** [comment]
Just opened the app from the Menu Bar and it says granted and contacts are syncing. Weird. Thank you (again) for the help!

**Comment by Philantrop** [comment]
For others who come here from a search and don't like Discord (F/OSS Matrix for the win!) or need more help than comment 3 and what can be found behind the link on Discord: It's indeed the OpenCore Legacy Patcher which causes this problem and a kind soul documented the exact steps to fix it:

https://www.reddit.com/r/BlueBubbles/comments/10z0fhg/psa_getting_contacts_on_the_server/

**Comment by zlshames** [comment]
> For others who come here from a search and don't like Discord (F/OSS Matrix for the win!) or need more help than comment 3 and what can be found behind the link on Discord: It's indeed the OpenCore Legacy Patcher which causes this problem and a kind soul documented the exact steps to fix it:
> 
> https://www.reddit.com/r/BlueBubbles/comments/10z0fhg/psa_getting_contacts_on_the_server/

I'll add documentation to our docs with this info
