### ISSUE TITLE
Can't connect to server using custom URLs

### ISSUE THREAD

**Issue by bobbyl140** [BlueBubblesApp/bluebubbles-server#613]
I tried entering a custom URL (`https://bb.example.com`) that points to my inbound proxy, which the client initially seems to take, but while trying to sync messages it gives up before it even starts with a message that the server is offline. The same thing happens when using the LAN URL of `http://<mac>:1234`. I tried it using Cloudflare and it worked immediately, but I don't wish to use a third party service for this.

**Comment by zlshames** [comment]
can you hit your LAN URL address in your browser?

**Comment by bobbyl140** [comment]
Yeah, both the LAN URL and that of the proxy are visible with `Welcome to the BlueBubbles Server landing page!`

**Comment by zlshames** [comment]
and just to confirm, when you are on your WiFi, the same one that your Mac is on, you are unable to connect to BlueBubbles using the LAN URL?

**Comment by bobbyl140** [comment]
Also correct, it's reachable in a browser from all networks, and reachable from the client on no network.

**Comment by bobbyl140** [comment]
May have found the problem: I use a VPN called Tailscale, and when I just now tried connecting to the VPN IP, it worked. My guess is that that IP is assumed to be *the* LAN IP and the physical one doesn't get listened on. Is there a way I could override that? Or just listen on `0.0.0.0`?

**Comment by bobbyl140** [comment]
I can use my original inbound proxy setup and forward to the VPN IP, so I guess this is no longer an issue for me, but this could be a potential problem in the future.

**Comment by zlshames** [comment]
> May have found the problem: I use a VPN called Tailscale, and when I just now tried connecting to the VPN IP, it worked. My guess is that that IP is assumed to be _the_ LAN IP and the physical one doesn't get listened on. Is there a way I could override that? Or just listen on `0.0.0.0`?
> 
> EDIT: But the browser can reach it. I don't know what's going on...

Yeah, super odd, but good call out. Right now, the listening code is just: https://github.com/BlueBubblesApp/bluebubbles-server/blob/master/packages/server/src/server/api/http/index.ts#L217

Looks like I can add a hostname after the port, and should be able to set it to `0.0.0.0`. Might fix the issue? I'm not 100% sure what it defaults to. This SO post indicates that maybe it already defaults to 0.0.0.0, or maybe localhost... Not super clear:

https://stackoverflow.com/questions/33953447/express-app-server-listen-all-interfaces-instead-of-localhost-only

No harm in explicitly setting the hostname though. it won't go out in the next beta release coming today most likely, but will be in the final release

**Comment by zlshames** [comment]
> I can use my original inbound proxy setup and forward to the VPN IP, so I guess this is no longer an issue for me, but this could be a potential problem in the future.
> 
> EDIT: I changed the proxy to the VPN IP, and it does begin to sync, but then it says the server is offline and gives up. EDIT 2: I can reopen the app and it shows messages, but this is the connection status: <img alt="Screenshot 2024-01-31 at 5 09 01 PM" width="469" src="https://private-user-images.githubusercontent.com/61990607/301323688-6d2f32af-1a4a-4d4b-a970-d752e56cf849.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3OTg5MTQsIm5iZiI6MTcwNjc5ODYxNCwicGF0aCI6Ii82MTk5MDYwNy8zMDEzMjM2ODgtNmQyZjMyYWYtMWE0YS00ZDRiLWE5NzAtZDc1MmU1NmNmODQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDE0NDMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ODU5M2YxMjBjZjRmNTYxY2U5MTc1MWYwMzFhMTkwYzc3M2EyY2VlMjMxYTU3Yzg4YTg3Mjk1NWExZjY1OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-QiZzNtiGdpVKARViTDV1khObnIvIYfSNNkMyAGVvm0"> I assume I'm doing something wrong with my proxy setup.

Maybe your proxy is not forwarding websocket stuff? im not totally sure, but I'm leaning towards an environment/setup issue. Maybe the hostname change will fix it, but I don't think so (for the socket disconnect issue specifically)

**Comment by bobbyl140** [comment]
I'm not sure either, I just checked and the module for proxying websockets is enabled. I have had a few other minor problems with my setup, so I'm sure there's something I'm not doing. But thanks anyways, sorry for the false issue.

**Comment by bobbyl140** [comment]
Although wait, I might know what's wrong. I am proxying with an `http://` URL, and not a `ws://` one. Is there a path that the websocket follows that I can statically proxy? If I need to proxy `/` then I'm not sure what to do. 

Still not sure about the LAN URL thing, but what you said about adding a hostname might do it.

**Comment by bobbyl140** [comment]
> That, I'm not sure of. We don't utilize a specific URL path for websocket connections.

Well I got it working with the LAN IP, I realize now if I ever need remote access I always have SSH port forwarding. My overall suggestion for this kind of setup though, is maybe put the websocket at (say) `/ws/` just so that you could do something like:

```
ProxyPass /ws ws://10.0.0.2:1234/ws/
ProxyPassReverse /ws ws://10.0.0.2:1234/ws/

ProxyPass / http://10.0.0.2:1234/
ProxyPassReverse / http://10.0.0.2:1234/
```

Without the ability to separate HTTP and Websocket connections, AFAIK you can do it by matching proxy rules to protocol, as in the following pseudocode:

```
if "http(s)://*":
  proxy to http://10.0.0.2

if "ws(s)://*":
  proxy to ws://10.0.0.2
```

I will try *actually* writing that when I'm fresh tomorrow morning and report back. But at this point the issue is clearly user error.

**Comment by bobbyl140** [comment]
Give me 5 minutes to set that in the config, and I'll report back.

**Comment by bobbyl140** [comment]
Sorry that took a while, I had some trouble configuring Apache. I did get it to work, with the following config (snippet):

```
        ProxyPass / http://(IP):(port)/
        ProxyPassReverse / http://(IP):(port)/

        RewriteCond %{HTTP:Upgrade} =websocket
        RewriteRule /socket.io/(.*) ws://(IP):(port)/socket.io/$1 [P,L]
```
