### ISSUE TITLE
Contacts with middle names are displayed incorrectly

### ISSUE THREAD

**Issue by bobbyl140** [BlueBubblesApp/bluebubbles-server#614]
I have a few contacts with the middle name field filled out, and when manually importing them, they are imported as `Middle First Last` rather than `First Middle Last`. I can't say if this also happens with automatic importing, I couldn't get it to work as per #613.

EDIT: I meant #612. I'm very sorry I had the wrong number!

**Comment by zlshames** [comment]
Any chance you can grab a sample from the VCF file and redact the PII and replace it with sample data? Just so I have something to go off of

**Comment by bobbyl140** [comment]
Yeah, here is a contact for a fictitious person whose full name is "John James Appleseed". When importing it manually, the Display Name becomes "James John Appleseed". (ZIPped for GitHub requirements. I can upload elsewhere if you need!)
[John James Appleseed.vcf.zip](https://github.com/BlueBubblesApp/bluebubbles-server/files/14188095/John.James.Appleseed.vcf.zip)

**Comment by zlshames** [comment]
Fixed, my development branch. Thanks.
