### ISSUE TITLE
Bluebubbles sticky keys

### ISSUE THREAD

**Issue by crockpotveggies** [BlueBubblesApp/bluebubbles-server#623]
Using a Macbook Air M1, 2020 on macOS 14.2.1 (23C71)

Installed latest stable version from Homebrew cask. After setting up the server, my Mac started to behave as if it had sticky keys and the arrow keys would act as if they were constantly pressed, even though there was no physical contact nor a mechanical issue.

It sort of acted like a keylogger was installed. This seemed to start after I set up an ngrok reverse proxy.

The issue persisted even after a restart and despite Bluebubbles not starting up on boot.

**Comment by SpaceSaver** [comment]
What version does it identify as?

**Comment by SpaceSaver** [comment]
Is sticky keys in fact still off?

**Comment by zlshames** [comment]
> Using a Macbook Air M1, 2020 on macOS 14.2.1 (23C71)
> 
> Installed latest stable version from Homebrew cask. After setting up the server, my Mac started to behave as if it had sticky keys and the arrow keys would act as if they were constantly pressed, even though there was no physical contact nor a mechanical issue.
> 
> It sort of acted like a keylogger was installed. This seemed to start after I set up an ngrok reverse proxy.
> 
> The issue persisted even after a restart and despite Bluebubbles not starting up on boot.

does uninstalling fix the issue? Also, why would you think a keylogger would operate that way. Wouldn't they _not_ want you to know something is up? Anyways... I don't really think it's BlueBubbles doing this. Definitely the first time I'm hearing about an issue like this. Are you using a remote access software to control your mac? Could it just be your keyboard?

**Comment by zlshames** [comment]
Closing this issue. No response, and I'm sure the issue is technically unrelated to BB
