### ISSUE TITLE
Unsent Attachments Aren't Updated

### ISSUE THREAD

**Issue by joshuafhiggins** [BlueBubblesApp/bluebubbles-server#637]
When unsending an attachment, either as the recipient or sending, the BlueBubbles Server doesn't broadcast the updated message event that the attachment was deleted. This means that, if the BueBubbles client didn't delete the attachment, unsent attachments aren't removed. If the client didn't download the attachment before it was unsent, then the BB client fails to fetch the attachment. This can be tested by unsending an attachment in iMessage and any clients are not notified of the change. If one client unsends it, then others will not see it removed. 

This occurs on the latest release, 1.9.6, even with the new feature to include edit and unsends on the updated message event.

**Comment by cameronaaron** [comment]
bump

**Comment by zlshames** [comment]
Do you know if this issue happens when individual attachments are sent, or only when multiple attachments are sent

**Comment by zlshames** [comment]
Ok, i think i figured it out. When a message goes unsent, the messageInfoSummary gets updated like so:
```
[1]   messageSummaryInfo: [
[1]     { ust: true, retractedParts: [ 0 ], originalTextRange: [ 0, 62 ] }
[1]   ],
```

I just need to detect that

**Comment by joshuafhiggins** [comment]
> Do you know if this issue happens when individual attachments are sent, or only when multiple attachments are sent

Sorry for the late reply, it's both.

**Comment by zlshames** [comment]
Fixed, my `development` branch
