### ISSUE TITLE
Vm Mac wont send videos

### ISSUE THREAD

**Issue by Wusgoodindahood** [BlueBubblesApp/bluebubbles-server#644]
Hi. Sending messages with bluebubbles works perfectly, except for videos. Regardless of the fact I have private API features enabled, followed steps correctly and everything, videos won't send at all on my vm Mac. I reset and created a brand new vm multiple times to no avail. I have Ethernet connected to reduce Internet lag as well. I attached an image of the blue progress bar when sending videos, which eventually says not delivered. Please help , thank you !
![IMG_20240430_180750110~2](https://github.com/BlueBubblesApp/bluebubbles-server/assets/65263407/e30e2c8e-daf2-4c5c-ad3c-6f4a2f5d229f)
![IMG_20240430_180906882](https://github.com/BlueBubblesApp/bluebubbles-server/assets/65263407/34edcf11-fb92-470d-bffb-b48aca9383b7)

**Comment by zlshames** [comment]
Are you able to send the same attachment when sending directly through the Messages app, rather than BlueBubbles?

**Comment by zlshames** [comment]
@Wusgoodindahood any update? Otherwise, I'm going to close this due to lack of information

**Comment by cameronaaron** [comment]
It kinda looks like a ban to me potentially if its not working native

**Comment by zlshames** [comment]
Closing, stale.
