### ISSUE TITLE
auto restart if the server crashes 

### ISSUE THREAD

**Issue by cameronaaron** [BlueBubblesApp/bluebubbles-server#648]
It would be nice if the install created a launch agent that could allow it to restart it when if it crashes

**Comment by Scr0nch** [comment]
Here is what I did to achieve this:

1. Copy the following file contents to `~/Library/LaunchAgents/app.bluebubbles.plist`:
    ```xml
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
        <dict>
            <key>Label</key>
            <string>app.bluebubbles</string>
            <key>Program</key>
            <string>/Applications/BlueBubbles.app/Contents/MacOS/BlueBubbles</string>
            <key>RunAtLoad</key>
            <true/>
            <key>KeepAlive</key>
            <true/>
        </dict>
    </plist>
    ```

    Note that `RunAtLoad` will start this launch agent when loaded (which is determined below) and `KeepAlive`, since it is set to `true`, will indiscriminately restart BlueBubbles when it exits. As I was researching this, I found that not specifying that the agent should not be restarted when it exits successfully may cause problems with software updates ([source](https://github.com/tjluoma/launchd-keepalive)), but I haven't had the chance to test this yet.
2. Disable the built-in autostart:
![Screenshot 2024-05-17 at 12 43 40 PM](https://github.com/BlueBubblesApp/bluebubbles-server/assets/55505812/2bdf63bb-287a-44f1-8d03-19f441ab34dd)

3. Install the launch agent and load it after the current user graphically logs in:
    ```shell
    launchctl bootstrap gui/$(id -u $(whoami)) ~/Library/LaunchAgents/app.bluebubbles.plist
    ```
5. Immediately start the launch agent (only necessary for the first time):
    ```shell
    launchctl kickstart gui/$(id -u $(whoami))/app.bluebubbles
    ```

Some additional notes:
- To uninstall the launch agent:
    ```shell
    launchctl remove app.bluebubbles
    ```
- To print information about the launch agent:
    ```shell
    launchctl print gui/$(id -u $(whoami))/app.bluebubbles
    ```

**Comment by zlshames** [comment]
Thanks @Scr0nch I've turned this into an official guide! https://docs.bluebubbles.app/server/basic-guides/autostart-server-after-crash

**Comment by cameronaaron** [comment]
I have no clue why this has never worked for me in practice it would still be very nice if this was bundled into the bluebubbles application

**Comment by zlshames** [comment]
> I have no clue why this has never worked for me in practice it would still be very nice if this was bundled into the bluebubbles application

I might be able to have the server do it, but it may require admin privileges. I'll have to see. 

It probably didn't work for you because the path that he included as the program variable is in the system applications folder. Whole yours is likely in your User applications folder.

**Comment by zlshames** [comment]
Ok i was able to add it as a feature on the server

**Comment by cameronaaron** [comment]
Thank you!

**Comment by illgitthat** [comment]
@zlshames @cameronaaron Do either of you know if there is an easy solution for running the bluebubbles server on reboot (instead of on login)? I guess I should just manually change from a launch agent to a launch daemon?

**Comment by cameronaaron** [comment]
@illgitthat It needs to hook into things that are part of an individual use imessage, facetime etc. Having it run when the OS is booting likely would not do you much good. I think the best solution is to just set auto login

**Comment by illgitthat** [comment]
Right, good point!

I'll give this a shot in combination: https://support.apple.com/en-us/102316#

**Comment by zlshames** [comment]
yeah the server can't run as "root" (without a user) because it won't know which iMessage DB to look in when the Messages app runs. Which is required.
