### ISSUE TITLE
Continuously kicked out of iMessage

### ISSUE THREAD

**Issue by 825i** [BlueBubblesApp/bluebubbles-server#650]
After going through the lengthy process on a VM Mac and signing in via the Settings panel to my Apple account. I am getting kicked out non-stop by iMessage/Facetime.

1. Basically I boot my VM Mac.
2. Bluebubbles opens
3. iMessage, Find My Mac and Facetime open
4. I login to iMessage
5. It logs in successfully
6. It kicks me out after 10 seconds and asks me to login again

This happens over and over. Bluebubbles keeps launching iMessage and it keeps bouncing in the dock over and over popping up to get me to login. Bluebubbles server also doesn't record my Apple ID email. It's just blank.

It does temporarily show the email when I am logged in, but it logs me out afterward.

MacOS: Big Sur 11.7.10
Bluebubbles: 1.9.7
Everything is "green text" authorized, et cetera.
SIP Disabled: Pass
MacOS Permissions: Accessibility & Full Disk Permissions (both pass)

I've also tried disabling the private API even though I have full permissions pass for it. iMessage kicks me out regardless.
Even if I close Bluebubbles entirely, I still can't stay signed in to iMessage.

Debug log is giving me this:
![image](https://github.com/BlueBubblesApp/bluebubbles-server/assets/58630825/7f69fb03-bdd5-4f56-8a51-31efacad887f)
![image](https://github.com/BlueBubblesApp/bluebubbles-server/assets/58630825/20e87d69-fa28-4796-af10-ef289ed7c19a)

I am also getting this from system.log:
![image](https://github.com/BlueBubblesApp/bluebubbles-server/assets/58630825/af8fe8cc-441b-4557-b692-7a1f9bedd9dc)

**Comment by SpaceSaver** [comment]
This is an issue with your Mac VM, not BB.  [](https://reddit.com/nj8yeu/)

**Comment by zlshames** [comment]
Closing, @SpaceSaver is correct.
