### ISSUE TITLE
Server sync time getting progressively worse and can be made better by restarting the server

### ISSUE THREAD

**Issue by cameronaaron** [BlueBubblesApp/bluebubbles-server#656]
Hi so I have my machine synced up to the NIST time server. However my sync keeps getting worse and worse and I am not sure why. Restarting the server seems to help which makes me think there is something in the server itself that needs to be reset

**Comment by zlshames** [comment]
The server app? I wouldn't think that the server app would impact the system time. Or do you just mean macos itself

**Comment by cameronaaron** [comment]
I think it might be the way it is interpreting it or something. I am not sure why restarting the bluebubble server app would bring down the high system time indicator in status

**Comment by zlshames** [comment]
> I think it might be the way it is interpreting it or something. I am not sure why restarting the bluebubble server app would bring down the high system time indicator in status

All the server does is run: `sntp time.apple.com` which will give the server something like this: `+0.083118 +/- 0.010981 time.apple.com 17.253.20.125`
