### ISSUE TITLE
Automatic Google Setup Process Failing

### ISSUE THREAD

**Issue by juil** [BlueBubblesApp/bluebubbles-server#661]
When using the Google login to automatically setup Firebase, it fails to create the project.

![Screenshot 2024-06-24 at 09 57 58](https://github.com/BlueBubblesApp/bluebubbles-server/assets/516726/4e751cbb-bfd0-49e3-97c2-08129984b0e5)

However, if I go into the **Manual Setup**, create a project named "BlueBubbles", and then try again using the Google login, it works.

![Screenshot 2024-06-24 at 10 03 41](https://github.com/BlueBubblesApp/bluebubbles-server/assets/516726/539a093b-e205-4fe9-9d90-b5bddd776e56)

**Comment by zlshames** [comment]
Yeah, this is a bit known. I've fixed it in my development branch i believe. Will be released within the next couple weeks
