### ISSUE TITLE
errors updating to v1.9.8 arm64 prerelease

### ISSUE THREAD

**Issue by d4tocchini** [BlueBubblesApp/bluebubbles-server#668]
Great news on native support for Apple Silicon!

I just updated a server (m1 mac mini  ventura13.6.7) from v1.9.7 to the v.1.9.8 prerelease. After opening the app I get series of many repeating error popups of the following saying Messages & Facetime quite unexpectedly.

<img width="294" alt="Screenshot 2024-07-11 at 4 48 38 PM" src="https://github.com/user-attachments/assets/75bc7e73-432d-4c7e-a769-98edd3bf89e8">

<img width="255" alt="Screenshot 2024-07-11 at 4 48 54 PM" src="https://github.com/user-attachments/assets/480fda3e-c75f-4f12-9a8e-d4c1fed21def">

Both Messages & FaceTime are consequently no longer open, but bluebubbles does boot a lot faster than before ;) I then tried manually opening Messages & FaceTime and testing if any API calls went through only to receive  500 Internal Server Errors.

Should I restart the state of the server? Let me know if there's anything else I can do / provide to help, thanks!

**Comment by d4tocchini** [comment]
After trying a fresh install, those FaceTime / Message popups showed up only when I tried to turn on the private API features in the onboarding flow.  Something w/ papi...

**Comment by zlshames** [comment]
Yeah I need to debug this some more. The issue is mainly that I don't have an m1 Mac to test against. So I'll need to work closely with one of you to make some test builds to help figure this thing out. 

I don't think the issue is how I'm building the private API dylib, but rather, how im calling the app

**Comment by HenryTheX** [comment]
it's related to Private API send method. If you turn off Private API Attachment send, then it wont crash server imesssage any more.
Waiting for developer to fix

**Comment by zlshames** [comment]
> it's related to Private API send method. If you turn off Private API Attachment send, then it wont crash server imesssage any more. Waiting for developer to fix

it's just related to the private api in general. Not a specific function within it.

**Comment by keithah** [comment]
Is this fixed? happy to test a build or give access to a test machine if thats helpful.

**Comment by zlshames** [comment]
> Is this fixed? happy to test a build or give access to a test machine if thats helpful.

From our research, it seem this may be a bug in macOS. This other GitHub issue & my comment explains a little bit of it: https://github.com/rofl0r/proxychains-ng/issues/481#issuecomment-2226832530

For some reason your architecture list is "empty", `''`. You can fix it by just adding a boot arg, as seen in this StackOverflow comment: https://stackoverflow.com/questions/67695609/building-for-arm64e-on-apple-silicon/70982791#70982791

Then reboot. I'm not sure there is anything I can do to fix it.
