### ISSUE TITLE
Adding a webhook for Find My location changes?

### ISSUE THREAD

**Issue by mehapps** [BlueBubblesApp/bluebubbles-server#679]
Would this be possible? Don't currently see it unless it falls under all events but that wouldn't be ideal either. Would be even better if we could filter by user as well but if that adds too much complexity then no worries!

**Comment by zlshames** [comment]
done, my dev branch

**Comment by mehapps** [comment]
That was fast thank you! I assume this will be pushed soon to a build?

**Comment by zlshames** [comment]
> That was fast thank you! I assume this will be pushed soon to a build?

It was like a 2 line change. It'll be released with next update, which is in the works. Finalizing it but also working on the android app, so I'm splitting time. No ETA but it's done
