### ISSUE TITLE
Feature Request: ban appeal server for the BlueBubbles discord server

### ISSUE THREAD

**Issue by yeet-dot-org** [BlueBubblesApp/bluebubbles-server#689]
Yes, I know it's off topic but I don't know where else to write this at.

I got banned from the Blue bubbles discord server for some reason, I never got a DM from a bot that told me why, and I honestly don't remember anymore. I think it would be great if there was an unban request discord server where we can appeal our ban.

**Comment by cameronaaron** [comment]
Please close

**Comment by yeet-dot-org** [comment]
> Please close

I don't really know where else to post this, so I'm posting it here. Let me know where I can post my ban appeal or get in contact with someone that would be in charge.

**Comment by cameronaaron** [comment]
Why did you get banned

**Comment by zlshames** [comment]
Are you gonna say what your username is?

**Comment by yeet-dot-org** [comment]
> Why did you get banned

I honestly wish I knew, I never got a dm from a bot and one day I noticed it was missing from my server list.
my user name is ( usernamefunnysomething. ) with the dot
![Screenshot_20241112-221723](https://github.com/user-attachments/assets/716d1ce9-d6ac-4436-a43c-1f757c7c1df7)

**Comment by zlshames** [comment]
> > Why did you get banned
> 
> I honestly wish I knew, I never got a dm from a bot, I just noticed one day the bluebubbles discord it was missing from my server list. my user name is ( usernamefunnysomething. ) with the dot ![Screenshot_20241112-221723](https://private-user-images.githubusercontent.com/71843354/385582828-716d1ce9-d6ac-4436-a43c-1f757c7c1df7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0ODE0MjQsIm5iZiI6MTczMTQ4MTEyNCwicGF0aCI6Ii83MTg0MzM1NC8zODU1ODI4MjgtNzE2ZDFjZTktZDZhYy00NDM2LWE0M2MtMWY3NTdjN2MxZGY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDA2NTg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MDA3YzVlMzAxOTFkNDY2NDZkNzczNDM0MDdjNzI4NmQ5ZDFkZmNkNWJkZDQ3M2IzMTU3ZDY4N2E2MzVmZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xUC4pfh8xnUTGki1UKEzNzPBAOjmgyu0iHutMJiwsNQ)

I've unbanned you but next time there's any rule breaking it'll be permanent
