### ISSUE TITLE
Get iMessage Availability Broken

### ISSUE THREAD

**Issue by JUSTINMKAUFMAN** [BlueBubblesApp/bluebubbles-server#699]
I have been using the iMessage availability API (`api/v1/handle/availability/imessage`) to determine whether a phone number is eligible for iMessage and it has been working great until recently. 

A few days ago, I started seeing a bunch of `"available": false` responses for numbers that I know for a fact _are_ iMessage-enabled. 

Some observations:

1. This incorrect response does not happen with all numbers; only some
2. Sometimes, if I wait a bit, it returns the correct response for a number for which it recently returned an incorrect response
3. I am running the current release build of BlueBubbles Server on macOS 14.5 with SIP disabled
4. Nothing changed on my server between the period when this was working and when I first noticed this issue

It is possible (though I'm not 100% sure) that this started happening around the time iOS 18 was released to the public. Not sure if there's anything worth poking at there.

Is anyone else experiencing this?

![iMessageAvailabilityBug](https://github.com/user-attachments/assets/2492b331-bf58-44e4-83ee-44d975d637b6)

**Comment by mehapps** [comment]
> Sometimes, if I wait a bit, it returns the correct response for a number for which it recently returned an incorrect response
This seems like the biggest factor, sometimes even on real Macs, when you type a phone number it shows text message hastily (which is likely what BB sees and returns) and then shows iMessage after polling. Maybe try a server restart?

**Comment by tneotia** [comment]
Hi Justin, can you let me know the frequency and quantity of your requests to the handle availability endpoint? Like are you using this to check a large list of contacts very quickly?

**Comment by JUSTINMKAUFMAN** [comment]
> Hi Justin, can you let me know the frequency and quantity of your requests to the handle availability endpoint? Like are you using this to check a large list of contacts very quickly?

I do a bit of both (occasional bulk syncing of contact capabilities and pre-message-send rechecking).

Upon further investigation, I believe this is not a blue bubbles error but rather a latency or desync issue with the iMessage availability API itself, as I can reproduce this bug outside of the blue bubbles interface. As such, I will close this issue.

Thanks!

**Comment by tneotia** [comment]
Hi Justin, just want to let you know that if doing this in bulk, it is a very likely possibility, best practices are to not request the endpoint over and over again, instead request a minimum of 5-10 seconds apart randomly.

**Comment by defaultcomputer1980** [comment]
Hi there, I need help setting the blue bubble helper up to do the same thing as in l phone numbers in large quantities to see if they are registered for iMessage
