### ISSUE TITLE
"Accounts managed by Family Link are not allowed to sign in here." error when trying to sync google contacts with a supervised account

### ISSUE THREAD

**Issue by nicotriballier** [BlueBubblesApp/bluebubbles-server#721]
Hi team,
I've configure a BB server for my daughter on Android (i'm supervising her google account via Google Family Link).
Receiving/sending messages work fine.
The only issue at this moment is synching contacts.
I'm running the BB server on a mac mini - on that mac mini in iMessage i can see that the name of each recipient is properly displayed, as it's coming from the contact app (there are contacts from icloud and contacts from google [aka 'internet account'].
But in the BB client on Android all recipients shows as their phone numbers and not their names.
I've been trying to restart the BB server, played around with the BB server 'refresh contact' options - no progress.
Then I saw that BB server offers to signin using google to sync the google contacts directly to make them available to the BB clients. I tried to signin with my daughter's account, got prompted to sign in using the app's web view but I got the error "Accounts managed by Family Link are not allowed to sign in here.". Note that I dont get that error when I signin in Chrome on the same device. It looks like something is off with the app's webview. Question - could u update the app so it doesn't show a web view and instead prompt to signin in Chrome directly? (like Slack does)
Thanks in advance!
PS - awesome work building BB!!!

**Comment by jjoelj** [comment]
The BB client doesn't get contacts from the server. It should show contact names provided you've granted the contacts permission to the android app and the contacts exist on the phone.

**Comment by nicotriballier** [comment]
Hi Joel, thank you for the super quick response! I just manually granted the BB client access to the contact app and it immediately solved the problem, thanks a lot!!
