### ISSUE TITLE
Close messages and retry to rename-group on fail

### ISSUE THREAD

**Issue by maxwellfortney** [BlueBubblesApp/BlueBubbles-Server#94]
![image](https://user-images.githubusercontent.com/29241388/98200319-5a90dd80-1efb-11eb-8d51-20b9ba2307b6.png)

Failed to rename group, but closing messages and trying again resulted in success.

**Comment by zlshames** [comment]
Before _any_ accessibility applescript execution, I restart the Messages app prior to starting the script.
