### ISSUE TITLE
Unable to connect to the server with my own DDNS and open port

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Server#95]
![No DDNS](https://user-images.githubusercontent.com/53708281/98577348-d25b6100-2289-11eb-93bc-a0e05f637a2e.jpg)
Perhaps on the alternatively ngrok url line, a line to enter the DDNS address can be added too. Also, the port is forwarded over TCP, does it have to be forwarded over UDP as well?

**Comment by zlshames** [comment]
Hey @CSab6482, thanks for the report! This looks like an older version of the Android App. Please join our Discord to get an updated version of the app that should work for you. If not, we can troubleshoot in the Discord

**Comment by zlshames** [comment]
Closing due to no additional information provided. We have officially released our Android app to the playstore as of now, so please try to use that updated version of the app and try again!
