### ISSUE TITLE
Automatically convert .caf attachments to .mp3 

### ISSUE THREAD

**Issue by maxwellfortney** [BlueBubblesApp/BlueBubbles-Server#96]
`/usr/bin/afconvert -f caff -d LEI16 {INPUT} {OUTPUT}`

**Comment by zlshames** [comment]
My branch

**Comment by zlshames** [comment]
It was more complicated than the command above. I needed to convert from caff to mp3, so it looked more like `/usr/bin/afconvert -f m4af -d aac {INPUT} {OUTPUT}`
