### ISSUE TITLE
Unable to connect to server.

### ISSUE THREAD

**Issue by LP0101** [BlueBubblesApp/BlueBubbles-Server#97]
I'm planning to expose the server myself, so not using ngrok.

I have the client running on a macOS VM, on `192.168.10.122:1234`. I'm able to successfully open a connection to that IP/port using telnet, so I know that bluebubbles is listening. If I try to connect with the incorrect credentials, I get an incorrect credentials error. But when I connect with the correct credentials, it errors out.
![image](https://user-images.githubusercontent.com/16864921/99855105-138a2580-2b54-11eb-9689-556ffb35973c.png)

Server is on macOS mojave, running under KVM. I've tried both Windows and Linux for the client.

**Comment by maxwellfortney** [comment]
Desktop client requires `http://` before your ip address

**Comment by zlshames** [comment]
Can you please verify that BlueBubbles has Full Disk Access in your Mac's privacy permissions? If it does, can you remove it then re-add it? If this isn't the issue, we can diagnose further
